// Eligibility-screen data source for the /screens/ pages and the per-market
// eligibility_screens field. Generated by screen_eligibility.py --write
// (repo root) against the same bundle universe.ts reads — regenerate whenever
// the bundle changes. Statuses are the public vocabulary (eligible / review /
// not_eligible — never pass/fail, so a jurisdiction-scoping fact cannot be
// misread as market quality). Spec: outputs/clearmarket/eligibility-screens-decision.md.
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

export type EligibilityStatus = 'eligible' | 'review' | 'not_eligible';

export type EligibilityRecord = {
  regime: string;
  status: EligibilityStatus;
  reasons: string[];
  cluster?: string | null; // review judgment-cluster key (review rows only)
  bucket: string | null;
  source_commitment: string | null;
  source_class: string | null;
  rcg_grade: string | null;
  screened_at: string;
};

export type ReviewCluster = {
  key: string;
  label: string;
  reason: string;
  market_count: number;
  event_count: number;
  example_events: string[];
};

export type ScreenSummary = {
  regime: string;
  regime_name: string;
  screen_version: string;
  screened_at: string;
  venue: string;
  funnel: {
    in_scope: number;
    candidate_category: number;
    min_maturity: number;
    eligible: number;
    review: number;
    not_eligible: number;
  };
  eligible_buckets: Record<string, number>;
  eligible_no_committed_source: number;
  review_reasons: Record<string, number>;
  review_clusters: ReviewCluster[];
};

const REGIME = 'ciro-26-0076';

function load<T>(rel: string): T | null {
  try {
    return JSON.parse(readFileSync(resolve(process.cwd(), rel), 'utf-8')) as T;
  } catch {
    // Screens are an optional layer: the site must build even if the screen
    // step didn't run (the pages render an "unavailable" state instead).
    return null;
  }
}

const byMarket = load<Record<string, EligibilityRecord>>(`data/eligibility-${REGIME}.json`);
const summary = load<ScreenSummary>(`data/eligibility-${REGIME}-summary.json`);

export function getScreenSummary(): ScreenSummary | null {
  return summary;
}

export function getEligibility(marketId: string): EligibilityRecord | null {
  return byMarket?.[marketId] ?? null;
}

export function getMarketIdsByStatus(status: EligibilityStatus): string[] {
  if (!byMarket) return [];
  return Object.entries(byMarket)
    .filter(([, r]) => r.status === status)
    .map(([id]) => id);
}

// Human-readable copy for reason codes (kept here so every surface says the
// same thing). The Section refs point at Appendix A of bulletin 26-0076.
export const REASON_COPY: Record<string, string> = {
  category_not_permitted: 'category outside the Appendix A Section 1 buckets',
  under_min_maturity: 'term to maturity under 30 days (Section 2)',
  no_resolution_date: 'no parseable resolution date (Section 2 cannot be evidenced)',
  category_interpretation_s1: 'Section 1 interpretation open — the "such as" examples are macro statistics',
  category_not_enumerated_s1: 'category not enumerated in Section 1 (crypto)',
  political_nature_s3: 'Section 3 political-language flag inside a permitted category',
  venue_out_of_scope: 'venue out of scope for this regime',
};
