// Turns the enriched universe bundle into D1 reload SQL.
// Emits api/seed/schema.sql (DDL, idempotent — CREATE IF NOT EXISTS, never drops events/markets)
// and api/seed/seed.sql (batched UPSERTs). Also prints chosen demo slugs.
//
// OWNERSHIP MODEL (2026-10-08): the laptop pipeline owns DESCRIPTIONS (question, sources, grade,
// linking, ladders, tags); production owns STATE (status, prices, volumes, clocks, screens).
// A reload therefore:
//   - INSERTs new events/markets; on conflict UPDATEs description columns only;
//   - stamps bundle_vintage on every row it saw; bumps row_changed_at ONLY where a description
//     column actually differs (so /v1/marks?since= consumers see real changes, nothing else);
//   - retires still-open markets the bundle no longer carries: status='delisted' + delisted_at,
//     through the change clock (visible to incremental consumers; never deleted);
//   - never touches resolution_log / marks_daily / cron_runs / feed_meta.
//
//   node api/scripts/export-d1.mjs [path-to-bundle] [--with-resolution-log]
//
// Default bundle: web/data/universe-enriched-linked.json
// --with-resolution-log: bootstrap-only (from-scratch DB). Emits INSERT OR IGNORE so it is
//   idempotent, but production D1 is the system of record for the ledger — do not pass it routinely.
// Production prerequisite for the first reload on this path: api/reload-upsert-migration.sql
//   (adds bundle_vintage / delisted_at to the live tables).
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO = resolve(__dirname, '..', '..');
const argPaths = process.argv.slice(2).filter((a) => !a.startsWith('--'));
const BUNDLE = argPaths[0] ?? resolve(REPO, 'web', 'data', 'universe-enriched-linked.json');
const SEED_DIR = resolve(__dirname, '..', 'seed');

const bundle = JSON.parse(readFileSync(BUNDLE, 'utf-8'));
const events = bundle.events ?? [];
const markets = bundle.markets ?? [];

// Reload identity. VINTAGE is the bundle's own build time (deterministic across re-exports) and is
// what rows get stamped with; NOW_SQL is evaluated by D1 at apply time and is what the change clock
// gets — a consumer keyed on since= must see the reload at the moment it landed, not when the
// bundle was built days earlier.
const VINTAGE = bundle._meta?.generated_at ?? new Date().toISOString();
const NOW_SQL = `strftime('%Y-%m-%dT%H:%M:%fZ','now')`;

// Eligibility screens (optional layer): per-market records + summary, written by
// screen_eligibility.py --write. Serialized into markets.eligibility_screens as the
// public spec shape [{regime, screen_version, status, reasons, bucket, screened_at}]
// (eligibility-screens-decision.md). Seed builds fine without the files.
let eligByMarket = {};
let eligVersion = '';
try {
  // Read both into temporaries and assign only if BOTH parse: the two files
  // are only valid as a pair (a populated map with an empty screen_version
  // would seed 6k versionless records and break result traceability).
  const byMarket = JSON.parse(readFileSync(resolve(REPO, 'web', 'data', 'eligibility-ciro-26-0076.json'), 'utf-8'));
  const version = JSON.parse(readFileSync(resolve(REPO, 'web', 'data', 'eligibility-ciro-26-0076-summary.json'), 'utf-8')).screen_version;
  if (!version) throw new Error('summary has no screen_version');
  eligByMarket = byMarket;
  eligVersion = version;
  console.error(`eligibility: ${Object.keys(eligByMarket).length} screened markets (screen ${eligVersion})`);
} catch (e) {
  eligByMarket = {};
  eligVersion = '';
  console.error(`eligibility: screen data unavailable or incomplete (${e?.message ?? e}) — eligibility_screens will be NULL`);
}
const eligScreens = (marketId) => {
  const r = eligByMarket[marketId];
  if (!r) return null;
  return [{
    regime: r.regime, screen_version: eligVersion, status: r.status,
    reasons: r.reasons ?? [], permitted_category: r.permitted_category ?? r.bucket ?? null, screened_at: r.screened_at,
  }];
};
console.error(`bundle: ${events.length} events / ${markets.length} markets (schema ${bundle._meta?.schema})`);

// ---- SQL value helpers -------------------------------------------------
const q = (v) => {
  if (v === null || v === undefined) return 'NULL';
  if (typeof v === 'number') return Number.isFinite(v) ? String(v) : 'NULL';
  if (typeof v === 'boolean') return v ? '1' : '0';
  return `'${String(v).replace(/'/g, "''")}'`;
};
const json = (v) => (v === null || v === undefined ? 'NULL' : `'${JSON.stringify(v).replace(/'/g, "''")}'`);

// ---- schema ------------------------------------------------------------
const schema = `-- ClearMarket D1 schema (generated by export-d1.mjs)
-- Nothing is dropped. events/markets are upserted (description columns only; see header);
-- catalyst_calendar is derived data (20 catalyst types from a local file) — seed.sql clears and refills it.
CREATE TABLE IF NOT EXISTS events (
  event_id TEXT PRIMARY KEY,
  slug TEXT UNIQUE NOT NULL,
  question TEXT NOT NULL,
  category TEXT NOT NULL,
  tags TEXT,
  primary_market_id TEXT,
  event_type TEXT,            -- 'BINARY' | 'LADDER' (multinomial strike ladder)
  ladder_distribution TEXT,   -- JSON {direction, implied_band, strikes[]} for LADDER events (patch_ladders.py)
  catalyst_types TEXT,        -- JSON array of catalyst-type pointers: ["cpi","fomc","earnings:NVDA"]
  catalyst_dates TEXT,        -- JSON array of BESPOKE per-event catalysts only (Exa/FDA); recurring derived at read-time
  venue TEXT,
  editorial_notes TEXT,
  bundle_type TEXT,            -- categorical|date_ladder|strike_ladder|augmented_negrisk|singleton
  resolution_reference TEXT,   -- generic subject-free event resolution ontology (OCC class-level rule)
  rcg_factors TEXT,            -- JSON: the 5 LLM factor ratings + "why" reasoning (audit trail)
  is_demo INTEGER NOT NULL DEFAULT 0,
  published INTEGER NOT NULL DEFAULT 1,
  created_at TEXT,
  updated_at TEXT,
  bundle_vintage TEXT         -- _meta.generated_at of the bundle that last wrote this row (reload-upsert-migration 2026-10-08)
);
CREATE INDEX IF NOT EXISTS idx_events_category ON events(category);
CREATE INDEX IF NOT EXISTS idx_events_demo ON events(is_demo);

-- Shared catalyst calendar: type -> {label, source_url, dates[]}. The Worker joins
-- events.catalyst_types against this at read-time and windows by resolution date.
-- Refreshed monthly (recurring macro + demand-driven earnings); no per-event storage.
CREATE TABLE IF NOT EXISTS catalyst_calendar (
  type TEXT PRIMARY KEY,      -- 'cpi' | 'jobs' | 'gdp' | 'fomc' | 'earnings:<TICKER>'
  label TEXT NOT NULL,
  source_url TEXT NOT NULL,
  dates TEXT NOT NULL         -- JSON array of ISO dates
);

CREATE TABLE IF NOT EXISTS markets (
  market_id TEXT PRIMARY KEY,
  event_id TEXT NOT NULL,
  platform TEXT,
  platform_market_id TEXT,
  question_raw TEXT,
  description_raw TEXT,
  contract_type TEXT,
  settlement_currency TEXT,
  underlying_reference TEXT,
  group_item_title TEXT,       -- per-child subject (the OSI-symbol analog; composes underlying_reference)
  close_at TEXT,
  resolve_at TEXT,
  status TEXT,
  resolution_rules_raw TEXT,
  arbitration_model TEXT,
  resolution_proposer TEXT,
  resolution_source TEXT,
  source_citation TEXT,
  resolution_source_type TEXT,
  resolution_source_quality TEXT,
  source_commitment TEXT,
  source_commitment_subtype TEXT,
  source_of_record TEXT,       -- the committed authority the LLM identified (grade-only; display stays verbatim)
  resolution_source_list TEXT, -- JSON [{name,url,provenance}] — full venue-listed + prose-surfaced source set
  source_status TEXT,          -- stamped at enrich: platform_named | no_committed_source | no_source_stated
  source_mechanism TEXT,       -- single_authority | precedence | quorum
  source_hedge_text TEXT,
  resolution_clarity_grade TEXT,
  rcg_score INTEGER,
  rcg_caps TEXT,
  rcg_applied_factors INTEGER,
  rcg TEXT,                    -- JSON audit: per-factor {rating,engine,weight,points} + caps + commitment
  last_price REAL,
  volume_24h_usd REAL,
  volume_total_usd REAL,
  last_updated_at TEXT,      -- ISO; stamped by the hourly marks cron on every price write (NULL until first refresh)
  reconciled_at TEXT,        -- ISO; stamped by the daily reconcileStatus cron when it confirms a market's status vs the venue
  settlement_style TEXT,
  direction TEXT,
  threshold REAL,
  question_id TEXT,
  also_on TEXT,              -- JSON [{venue, market_id, price}] of the same question on other venues; NULL if unique
  tags TEXT,
  eligibility_screens TEXT,  -- JSON [{regime, screen_version, status, reasons, bucket, screened_at}]; rule-set fit, NOT market quality
  last_checked_at TEXT,      -- ISO; stamped by the hourly marks cron for EVERY market seen in a venue live feed (freshness-migration 2026-09-17)
  row_changed_at TEXT,       -- ISO; Worker commit clock — /v1/marks?since= and its cursor key on THIS column (commit-clock-migration 2026-09-18)
  bundle_vintage TEXT,       -- _meta.generated_at of the bundle that last wrote this row's descriptions (reload-upsert-migration 2026-10-08)
  delisted_at TEXT           -- ISO (= the vintage that retired it); set when a still-open market is absent from a reload; cleared if it reappears
);
CREATE INDEX IF NOT EXISTS idx_markets_event ON markets(event_id);
CREATE INDEX IF NOT EXISTS idx_markets_grade ON markets(resolution_clarity_grade);
CREATE INDEX IF NOT EXISTS idx_markets_platform ON markets(platform);
CREATE INDEX IF NOT EXISTS idx_markets_question ON markets(question_id);
CREATE INDEX IF NOT EXISTS idx_markets_platform_mkt ON markets(platform_market_id);
CREATE INDEX IF NOT EXISTS idx_markets_last_updated ON markets(last_updated_at);
CREATE INDEX IF NOT EXISTS idx_markets_last_checked ON markets(last_checked_at);
CREATE INDEX IF NOT EXISTS idx_markets_reconciled ON markets(reconciled_at);
CREATE INDEX IF NOT EXISTS idx_markets_row_changed ON markets(row_changed_at);
CREATE INDEX IF NOT EXISTS idx_markets_status ON markets(status);
CREATE INDEX IF NOT EXISTS idx_markets_vintage ON markets(bundle_vintage);

-- Auth (Option 3): free-key signup + per-day rate limiting.
CREATE TABLE IF NOT EXISTS api_keys (
  key TEXT PRIMARY KEY,
  email TEXT NOT NULL,
  created_at TEXT NOT NULL,
  daily_limit INTEGER NOT NULL DEFAULT 1000,
  revoked INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS usage (
  key TEXT NOT NULL,
  day TEXT NOT NULL,
  count INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (key, day)
);
CREATE TABLE IF NOT EXISTS spot (
  coin TEXT PRIMARY KEY,
  price_usd REAL,
  as_of TEXT
);

-- Per-call audit log: one row per data request to the REST API or MCP. Records WHAT was
-- queried (which endpoint/tool + the key argument), WHO (api key or ip), and from WHERE.
-- Operational table — IF NOT EXISTS so it persists across reseeds (like api_keys/usage).
CREATE TABLE IF NOT EXISTS call_log (
  ts TEXT NOT NULL,           -- ISO timestamp of the call
  surface TEXT NOT NULL,      -- 'rest' | 'mcp'
  action TEXT NOT NULL,       -- endpoint or MCP tool name (e.g. 'get_event', 'list_events')
  target TEXT,                -- the key argument: slug / market_id / JSON of filters
  requester TEXT,             -- 'key:<key>' if authenticated, else 'ip:<addr>'
  country TEXT,               -- Cloudflare-resolved country of the caller
  user_agent TEXT             -- request UA — crawlers self-identify (GPTBot, ClaudeBot, …)
);
CREATE INDEX IF NOT EXISTS idx_call_log_ts ON call_log(ts);

-- End-of-day price/volume history (one row per market per day). Hourly cron keeps
-- markets.last_price fresh in place; this table is the daily time-series captured at the
-- EOD cron hour, so wires can report multi-day moves + volume-spike baselines. Scoped to
-- the ~2,700 linked+primary markets the marks cron actually refreshes (others stay stale).
CREATE TABLE IF NOT EXISTS marks_daily (
  market_id TEXT NOT NULL,
  day TEXT NOT NULL,
  last_price REAL,
  volume_24h_usd REAL,
  volume_total_usd REAL,
  captured_at TEXT,
  price_as_of TEXT,          -- ISO; the market's last_updated_at at snapshot time (freshness-migration 2026-09-17)
  carried_forward INTEGER,   -- 1 when the market was not seen in any live feed in the 24h before the snapshot
  PRIMARY KEY (market_id, day)
);
CREATE INDEX IF NOT EXISTS idx_marks_daily_mkt ON marks_daily(market_id);

-- Run ledger + pipeline metadata (freshness-migration 2026-09-17). Operational tables —
-- IF NOT EXISTS so they persist across reseeds; listed here so a from-scratch DB is complete.
CREATE TABLE IF NOT EXISTS cron_runs (
  run_id TEXT NOT NULL,
  step TEXT NOT NULL,
  venue TEXT NOT NULL DEFAULT '',
  started_at TEXT,
  finished_at TEXT,
  fetched INTEGER,
  changed INTEGER,
  error TEXT,
  PRIMARY KEY (run_id, step, venue)
);
CREATE INDEX IF NOT EXISTS idx_cron_runs_step ON cron_runs(step, started_at);
CREATE TABLE IF NOT EXISTS feed_meta (
  key TEXT PRIMARY KEY,
  value TEXT,
  updated_at TEXT
);

-- Resolution log: append-only resolved-market history. SINCE 2026-10-04 PRODUCTION D1 IS THE
-- SYSTEM OF RECORD for this table — the Worker crons (sweep apply, kalshi_finalized, reconcile)
-- write it daily and a reseed must NOT drop or reseed it (the laptop file knows nothing about
-- cron-written rows). web/data/resolution-log.json is a site-build input only. Seeding happens
-- ONLY on a from-scratch bootstrap via: node export-d1.mjs --with-resolution-log
CREATE TABLE IF NOT EXISTS resolution_log (
  market_id TEXT NOT NULL,
  event_id TEXT NOT NULL,
  platform TEXT,
  event_type TEXT,            -- 'resolved' | 'status_change'
  occurred_at TEXT,           -- when it settled (venue settlement time; deadline only as fallback)
  occurred_basis TEXT,        -- 'venue_settlement' | 'deadline' (which of the two occurred_at holds)
  recorded_at TEXT,           -- pull date that first observed it
  from_value TEXT,            -- prior state (e.g. 'open'); NULL for legacy rows
  to_value TEXT,              -- 'YES' | 'NO' | 'PENDING' (resolved) | 'closed' (status_change)
  final_price REAL,
  source TEXT,
  source_ref TEXT,
  actor TEXT,
  PRIMARY KEY (market_id, occurred_at)
);
CREATE INDEX IF NOT EXISTS idx_resolution_log_event ON resolution_log(event_id);
`;

// ---- choose demo events (top A-grade by primary-market volume) ---------
const marketById = new Map(markets.map((m) => [m.market_id, m]));
const demoSlugs = events
  .filter((e) => e.primary_market_id)
  .map((e) => ({ e, pm: marketById.get(e.primary_market_id) }))
  .filter(({ pm }) => pm && pm.resolution_clarity_grade === 'A')
  .sort((a, b) => (b.pm.volume_total_usd ?? 0) - (a.pm.volume_total_usd ?? 0))
  .slice(0, 3)
  .map(({ e }) => e.slug);
const demoSet = new Set(demoSlugs);

// ---- seed --------------------------------------------------------------
// D1 caps a single SQL statement at 100KB. Batch by byte-size, not row-count,
// so long resolution-rules text can't blow the cap. Target ~60KB/statement.
const MAX_BYTES = 60000;
function chunkBySize(rows, prefix, suffix = '') {
  const stmts = [];
  let cur = [];
  const fixed = prefix.length + suffix.length + 2;
  let len = fixed;
  const flush = () => stmts.push(`${prefix}\n${cur.join(',\n')}${suffix ? `\n${suffix}` : ''};`);
  for (const r of rows) {
    if (cur.length && len + r.length + 2 > MAX_BYTES) {
      flush();
      cur = []; len = fixed;
    }
    cur.push(r); len += r.length + 2;
  }
  if (cur.length) flush();
  return stmts;
}

const eRows = events.map((e) => `(${[
  q(e.event_id), q(e.slug), q(e.question), q(e.category), json(e.tags),
  q(e.primary_market_id), q(e.event_type ?? 'BINARY'), json(e.ladder_distribution ?? null),
  json(e.catalyst_types ?? []), json(e.catalyst_dates ?? []), q(e.venue), q(e.editorial_notes),
  q(e.bundle_type), q(e.resolution_reference), json(e.rcg_factors ?? null),
  demoSet.has(e.slug) ? '1' : '0', e.published === false ? '0' : '1',
  q(e.created_at), q(e.updated_at), q(VINTAGE),
].join(',')})`);

// ---- catalyst calendar seed (type-keyed; read from data/catalyst-calendar.json) ----
const CAL_PATH = resolve(REPO, 'data', 'catalyst-calendar.json');
let calRows = [];
try {
  const cal = JSON.parse(readFileSync(CAL_PATH, 'utf-8'));
  const types = cal.types ?? {};
  calRows = Object.entries(types).map(([type, c]) =>
    `(${[q(type), q(c.label), q(c.source_url), json(c.dates ?? [])].join(',')})`);
  console.error(`catalyst calendar: ${calRows.length} types`);
} catch (err) {
  console.error(`WARN: no catalyst-calendar.json (${err.message}) — calendar table will be empty`);
}

const mRows = markets.map((m) => `(${[
  q(m.market_id), q(m.event_id), q(m.platform), q(m.platform_market_id),
  q(m.question_raw), q(m.description_raw), q(m.contract_type), q(m.settlement_currency),
  q(m.underlying_reference), q(m.group_item_title), q(m.close_at), q(m.resolve_at), q(m.status),
  q(m.resolution_rules_raw), q(m.arbitration_model), q(m.resolution_proposer),
  q(m.resolution_source), q(m.source_citation), q(m.resolution_source_type),
  q(m.resolution_source_quality), q(m.source_commitment), q(m.source_commitment_subtype),
  q(m.source_of_record), json(m.resolution_source_list ?? null), q(m.source_status),
  q(m.source_mechanism), q(m.source_hedge_text), q(m.resolution_clarity_grade), q(m.rcg_score),
  json(m.rcg_caps), q(m.rcg_applied_factors), json(m.rcg ?? null), q(m.last_price), q(m.volume_24h_usd), q(m.volume_total_usd),
  q(m.settlement_style), q(m.direction), q(m.threshold), q(m.question_id), json(m.also_on ?? null), json(m.tags), json(eligScreens(m.market_id)),
  q(VINTAGE), NOW_SQL,
].join(',')})`);

// ---- resolution log seed — BOOTSTRAP ONLY (see schema comment: prod D1 is the system of
// record since 2026-10-04; a routine reseed must not touch resolution_log). Opt in with
// `--with-resolution-log` only when seeding a from-scratch database.
const SEED_RESLOG = process.argv.includes('--with-resolution-log');
const RESLOG_PATH = resolve(REPO, 'web', 'data', 'resolution-log.json');
let rlRows = [];
if (SEED_RESLOG) try {
  const rlog = JSON.parse(readFileSync(RESLOG_PATH, 'utf-8'));
  rlRows = (Array.isArray(rlog) ? rlog : []).map((r) => `(${[
    q(r.market_id), q(r.event_id), q(r.platform), q(r.event_type),
    q(r.occurred_at), q(r.occurred_basis ?? null), q(r.recorded_at), q(r.from_value ?? null), q(r.to_value), q(r.final_price),
    q(r.source), q(r.source_ref), q(r.actor),
  ].join(',')})`);
  console.error(`resolution log: ${rlRows.length} resolved markets`);
} catch (err) {
  console.error(`WARN: no resolution-log.json (${err.message}) — resolution_log table will be empty`);
}

// ---- upsert column contracts ------------------------------------------
// Column order here MUST match the eRows / mRows value builders above.
const EVENT_COLS = ['event_id','slug','question','category','tags','primary_market_id','event_type','ladder_distribution','catalyst_types','catalyst_dates','venue','editorial_notes','bundle_type','resolution_reference','rcg_factors','is_demo','published','created_at','updated_at','bundle_vintage'];
const MARKET_COLS = ['market_id','event_id','platform','platform_market_id','question_raw','description_raw','contract_type','settlement_currency','underlying_reference','group_item_title','close_at','resolve_at','status','resolution_rules_raw','arbitration_model','resolution_proposer','resolution_source','source_citation','resolution_source_type','resolution_source_quality','source_commitment','source_commitment_subtype','source_of_record','resolution_source_list','source_status','source_mechanism','source_hedge_text','resolution_clarity_grade','rcg_score','rcg_caps','rcg_applied_factors','rcg','last_price','volume_24h_usd','volume_total_usd','settlement_style','direction','threshold','question_id','also_on','tags','eligibility_screens','bundle_vintage','row_changed_at'];
// Production-owned state on markets: a reload must never overwrite these on an existing row.
// (They are still INSERTed for brand-new markets, which have no production state yet.)
const MARKET_STATE_COLS = new Set(['market_id','status','last_price','volume_24h_usd','volume_total_usd','eligibility_screens','row_changed_at']);
const MARKET_DESC_COLS = MARKET_COLS.filter((c) => !MARKET_STATE_COLS.has(c));
// Columns whose change is a "description changed" event for since= consumers (bundle_vintage alone is not).
const MARKET_DIFF_COLS = MARKET_DESC_COLS.filter((c) => c !== 'bundle_vintage');

// Events carry no production-owned state: full refresh on conflict (updated_at = the vintage the
// Worker reports as dataset.bundle_vintage via MAX(updated_at)).
const EVENT_UPSERT = `ON CONFLICT(event_id) DO UPDATE SET\n  ${EVENT_COLS.filter((c) => c !== 'event_id').map((c) => `${c} = excluded.${c}`).join(',\n  ')}`;

// Markets: description columns only. A market retired by an earlier reload that reappears in the
// bundle is revived (status from the bundle, delisted_at cleared) and that counts as a change.
const MARKET_UPSERT = `ON CONFLICT(market_id) DO UPDATE SET
  ${MARKET_DESC_COLS.map((c) => `${c} = excluded.${c}`).join(',\n  ')},
  status = CASE WHEN markets.status = 'delisted' THEN excluded.status ELSE markets.status END,
  delisted_at = CASE WHEN markets.status = 'delisted' THEN NULL ELSE markets.delisted_at END,
  row_changed_at = CASE WHEN (markets.status = 'delisted'
    OR ${MARKET_DIFF_COLS.map((c) => `excluded.${c} IS NOT markets.${c}`).join('\n    OR ')})
    THEN ${NOW_SQL} ELSE markets.row_changed_at END`;

// Retirement: still-open markets this bundle did not carry. Runs AFTER the upserts so bundle_vintage
// is current on every market the bundle knows. Resolved/closed markets are left alone (history).
const RETIRE_SQL = `UPDATE markets SET status = 'delisted', delisted_at = ${q(VINTAGE)}, row_changed_at = ${NOW_SQL}
WHERE status = 'open' AND (bundle_vintage IS NULL OR bundle_vintage <> ${q(VINTAGE)});`;

const batches = [
  ...chunkBySize(eRows, `INSERT INTO events (${EVENT_COLS.join(',')}) VALUES`, EVENT_UPSERT),
  ...chunkBySize(mRows, `INSERT INTO markets (${MARKET_COLS.join(',')}) VALUES`, MARKET_UPSERT),
  RETIRE_SQL,
  // catalyst_calendar is fully derived: clear + refill so retired catalyst types disappear and seed.sql is re-applyable.
  ...(calRows.length ? ['DELETE FROM catalyst_calendar;', ...chunkBySize(calRows, 'INSERT INTO catalyst_calendar (type,label,source_url,dates) VALUES')] : []),
  ...(rlRows.length ? chunkBySize(rlRows, 'INSERT OR IGNORE INTO resolution_log (market_id,event_id,platform,event_type,occurred_at,occurred_basis,recorded_at,from_value,to_value,final_price,source,source_ref,actor) VALUES') : []),
];

writeFileSync(resolve(SEED_DIR, 'schema.sql'), schema);
writeFileSync(resolve(SEED_DIR, 'seed.sql'), batches.join('\n'));

// meta sidecar the Worker can import for /health
writeFileSync(resolve(SEED_DIR, 'meta.json'), JSON.stringify({
  generated_at: bundle._meta?.generated_at ?? new Date().toISOString(),
  schema: bundle._meta?.schema ?? 'v0.2.0',
  event_count: events.length,
  market_count: markets.length,
  demo_slugs: demoSlugs,
}, null, 2));

console.error(`wrote schema.sql, seed.sql (${batches.length} batches), meta.json`);
console.error(`demo slugs: ${demoSlugs.join(' | ')}`);
