// Turns the enriched universe bundle into D1 seed SQL.
// Emits api/seed/schema.sql (DDL, idempotent) and api/seed/seed.sql (batched INSERTs).
// Also prints chosen demo slugs (the no-auth public events for Option-3 auth).
//
//   node api/scripts/export-d1.mjs [path-to-bundle]
//
// Default bundle: web/data/universe-enriched-full.json
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO = resolve(__dirname, '..', '..');
const BUNDLE = process.argv[2] ?? resolve(REPO, 'web', 'data', 'universe-enriched-linked.json');
const SEED_DIR = resolve(__dirname, '..', 'seed');

const bundle = JSON.parse(readFileSync(BUNDLE, 'utf-8'));
const events = bundle.events ?? [];
const markets = bundle.markets ?? [];
console.error(`bundle: ${events.length} events / ${markets.length} markets (schema ${bundle._meta?.schema})`);

// ---- SQL value helpers -------------------------------------------------
const q = (v) => {
  if (v === null || v === undefined) return 'NULL';
  if (typeof v === 'number') return Number.isFinite(v) ? String(v) : 'NULL';
  if (typeof v === 'boolean') return v ? '1' : '0';
  return `'${String(v).replace(/'/g, "''")}'`;
};
const json = (v) => (v === null || v === undefined ? 'NULL' : `'${JSON.stringify(v).replace(/'/g, "''")}'`);

// ---- schema ------------------------------------------------------------
const schema = `-- ClearMarket D1 schema (generated by export-d1.mjs)
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS markets;
CREATE TABLE events (
  event_id TEXT PRIMARY KEY,
  slug TEXT UNIQUE NOT NULL,
  question TEXT NOT NULL,
  category TEXT NOT NULL,
  tags TEXT,
  primary_market_id TEXT,
  event_type TEXT,            -- 'BINARY' | 'LADDER' (multinomial strike ladder)
  ladder_distribution TEXT,   -- JSON {direction, implied_band, strikes[]} for LADDER events (patch_ladders.py)
  catalyst_types TEXT,        -- JSON array of catalyst-type pointers: ["cpi","fomc","earnings:NVDA"]
  catalyst_dates TEXT,        -- JSON array of BESPOKE per-event catalysts only (Exa/FDA); recurring derived at read-time
  venue TEXT,
  editorial_notes TEXT,
  is_demo INTEGER NOT NULL DEFAULT 0,
  published INTEGER NOT NULL DEFAULT 1,
  created_at TEXT,
  updated_at TEXT
);
CREATE INDEX idx_events_category ON events(category);
CREATE INDEX idx_events_demo ON events(is_demo);

-- Shared catalyst calendar: type -> {label, source_url, dates[]}. The Worker joins
-- events.catalyst_types against this at read-time and windows by resolution date.
-- Refreshed monthly (recurring macro + demand-driven earnings); no per-event storage.
CREATE TABLE catalyst_calendar (
  type TEXT PRIMARY KEY,      -- 'cpi' | 'jobs' | 'gdp' | 'fomc' | 'earnings:<TICKER>'
  label TEXT NOT NULL,
  source_url TEXT NOT NULL,
  dates TEXT NOT NULL         -- JSON array of ISO dates
);

CREATE TABLE markets (
  market_id TEXT PRIMARY KEY,
  event_id TEXT NOT NULL,
  platform TEXT,
  platform_market_id TEXT,
  question_raw TEXT,
  description_raw TEXT,
  contract_type TEXT,
  settlement_currency TEXT,
  underlying_reference TEXT,
  close_at TEXT,
  resolve_at TEXT,
  status TEXT,
  resolution_rules_raw TEXT,
  arbitration_model TEXT,
  resolution_proposer TEXT,
  resolution_source TEXT,
  source_citation TEXT,
  resolution_source_type TEXT,
  resolution_source_quality TEXT,
  resolution_clarity_grade TEXT,
  rcg_score INTEGER,
  rcg_caps TEXT,
  rcg_applied_factors INTEGER,
  last_price REAL,
  volume_24h_usd REAL,
  volume_total_usd REAL,
  settlement_style TEXT,
  direction TEXT,
  threshold REAL,
  claim_sig TEXT,
  tags TEXT
);
CREATE INDEX idx_markets_event ON markets(event_id);
CREATE INDEX idx_markets_grade ON markets(resolution_clarity_grade);
CREATE INDEX idx_markets_platform ON markets(platform);
CREATE INDEX idx_markets_claim ON markets(claim_sig);

-- Auth (Option 3): free-key signup + per-day rate limiting.
CREATE TABLE IF NOT EXISTS api_keys (
  key TEXT PRIMARY KEY,
  email TEXT NOT NULL,
  created_at TEXT NOT NULL,
  daily_limit INTEGER NOT NULL DEFAULT 1000,
  revoked INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS usage (
  key TEXT NOT NULL,
  day TEXT NOT NULL,
  count INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (key, day)
);
CREATE TABLE IF NOT EXISTS spot (
  coin TEXT PRIMARY KEY,
  price_usd REAL,
  as_of TEXT
);

-- End-of-day price/volume history (one row per market per day). Hourly cron keeps
-- markets.last_price fresh in place; this table is the daily time-series captured at the
-- EOD cron hour, so wires can report multi-day moves + volume-spike baselines. Scoped to
-- the ~2,700 linked+primary markets the marks cron actually refreshes (others stay stale).
CREATE TABLE IF NOT EXISTS marks_daily (
  market_id TEXT NOT NULL,
  day TEXT NOT NULL,
  last_price REAL,
  volume_24h_usd REAL,
  volume_total_usd REAL,
  captured_at TEXT,
  PRIMARY KEY (market_id, day)
);
CREATE INDEX IF NOT EXISTS idx_marks_daily_mkt ON marks_daily(market_id);
`;

// ---- choose demo events (top A-grade by primary-market volume) ---------
const marketById = new Map(markets.map((m) => [m.market_id, m]));
const demoSlugs = events
  .filter((e) => e.primary_market_id)
  .map((e) => ({ e, pm: marketById.get(e.primary_market_id) }))
  .filter(({ pm }) => pm && pm.resolution_clarity_grade === 'A')
  .sort((a, b) => (b.pm.volume_total_usd ?? 0) - (a.pm.volume_total_usd ?? 0))
  .slice(0, 3)
  .map(({ e }) => e.slug);
const demoSet = new Set(demoSlugs);

// ---- seed --------------------------------------------------------------
// D1 caps a single SQL statement at 100KB. Batch by byte-size, not row-count,
// so long resolution-rules text can't blow the cap. Target ~60KB/statement.
const MAX_BYTES = 60000;
function chunkBySize(rows, prefix) {
  const stmts = [];
  let cur = [];
  let len = prefix.length + 1;
  for (const r of rows) {
    if (cur.length && len + r.length + 2 > MAX_BYTES) {
      stmts.push(`${prefix}\n${cur.join(',\n')};`);
      cur = []; len = prefix.length + 1;
    }
    cur.push(r); len += r.length + 2;
  }
  if (cur.length) stmts.push(`${prefix}\n${cur.join(',\n')};`);
  return stmts;
}

const eRows = events.map((e) => `(${[
  q(e.event_id), q(e.slug), q(e.question), q(e.category), json(e.tags),
  q(e.primary_market_id), q(e.event_type ?? 'BINARY'), json(e.ladder_distribution ?? null),
  json(e.catalyst_types ?? []), json(e.catalyst_dates ?? []), q(e.venue), q(e.editorial_notes),
  demoSet.has(e.slug) ? '1' : '0', e.published === false ? '0' : '1',
  q(e.created_at), q(e.updated_at),
].join(',')})`);

// ---- catalyst calendar seed (type-keyed; read from data/catalyst-calendar.json) ----
const CAL_PATH = resolve(REPO, 'data', 'catalyst-calendar.json');
let calRows = [];
try {
  const cal = JSON.parse(readFileSync(CAL_PATH, 'utf-8'));
  const types = cal.types ?? {};
  calRows = Object.entries(types).map(([type, c]) =>
    `(${[q(type), q(c.label), q(c.source_url), json(c.dates ?? [])].join(',')})`);
  console.error(`catalyst calendar: ${calRows.length} types`);
} catch (err) {
  console.error(`WARN: no catalyst-calendar.json (${err.message}) — calendar table will be empty`);
}

const mRows = markets.map((m) => `(${[
  q(m.market_id), q(m.event_id), q(m.platform), q(m.platform_market_id),
  q(m.question_raw), q(m.description_raw), q(m.contract_type), q(m.settlement_currency),
  q(m.underlying_reference), q(m.close_at), q(m.resolve_at), q(m.status),
  q(m.resolution_rules_raw), q(m.arbitration_model), q(m.resolution_proposer),
  q(m.resolution_source), q(m.source_citation), q(m.resolution_source_type),
  q(m.resolution_source_quality), q(m.resolution_clarity_grade), q(m.rcg_score),
  json(m.rcg_caps), q(m.rcg_applied_factors), q(m.last_price), q(m.volume_24h_usd), q(m.volume_total_usd),
  q(m.settlement_style), q(m.direction), q(m.threshold), q(m.claim_sig), json(m.tags),
].join(',')})`);

const batches = [
  ...chunkBySize(eRows, 'INSERT INTO events (event_id,slug,question,category,tags,primary_market_id,event_type,ladder_distribution,catalyst_types,catalyst_dates,venue,editorial_notes,is_demo,published,created_at,updated_at) VALUES'),
  ...chunkBySize(mRows, 'INSERT INTO markets (market_id,event_id,platform,platform_market_id,question_raw,description_raw,contract_type,settlement_currency,underlying_reference,close_at,resolve_at,status,resolution_rules_raw,arbitration_model,resolution_proposer,resolution_source,source_citation,resolution_source_type,resolution_source_quality,resolution_clarity_grade,rcg_score,rcg_caps,rcg_applied_factors,last_price,volume_24h_usd,volume_total_usd,settlement_style,direction,threshold,claim_sig,tags) VALUES'),
  ...(calRows.length ? chunkBySize(calRows, 'INSERT INTO catalyst_calendar (type,label,source_url,dates) VALUES') : []),
];

writeFileSync(resolve(SEED_DIR, 'schema.sql'), schema);
writeFileSync(resolve(SEED_DIR, 'seed.sql'), batches.join('\n'));

// meta sidecar the Worker can import for /health
writeFileSync(resolve(SEED_DIR, 'meta.json'), JSON.stringify({
  generated_at: bundle._meta?.generated_at ?? new Date().toISOString(),
  schema: bundle._meta?.schema ?? 'v0.2.0',
  event_count: events.length,
  market_count: markets.length,
  demo_slugs: demoSlugs,
}, null, 2));

console.error(`wrote schema.sql, seed.sql (${batches.length} batches), meta.json`);
console.error(`demo slugs: ${demoSlugs.join(' | ')}`);
