UPDATE events SET question='Will GOP Nominee be Ken Paxton AND General Election Winner be Republican for Jan 2027?' WHERE event_id='CM-EVT-KDQ9VR7CG1';
UPDATE events SET question='Will Labour win the 2026 Makerfield by-election?' WHERE event_id='CM-EVT-WLVBMGDF10';
UPDATE events SET question='Who will run for the Republican presidential nomination in 2028?' WHERE event_id='CM-EVT-HZLRXQM5W7';
UPDATE events SET question='Who will run for the Democratic presidential nomination in 2028?' WHERE event_id='CM-EVT-5H09B63413';
UPDATE events SET question='Will the margin of victory for Republicans in the U.S. Senate election in Texas be at least 3 percentage points?' WHERE event_id='CM-EVT-2R0YMZRC29';
UPDATE events SET question='Will the margin of victory for Ken Paxton in the U.S. Senate primary election in Texas be at least 12 percentage points?' WHERE event_id='CM-EVT-XS8332JBB4';
UPDATE events SET question='Will the margin of victory for Democrats in the Oregon''s 3rd District House election be at least 38 percentage points?' WHERE event_id='CM-EVT-98TTCLWRD8';
UPDATE events SET question='Will the margin of victory for Democrats in the Ohio''s 13th District House election be at least 2 percentage points?' WHERE event_id='CM-EVT-RL4DPXZ231';
UPDATE events SET question='Will the margin of victory for Democrats in the New Hampshire''s 2nd District House election be at least 4 percentage points?' WHERE event_id='CM-EVT-PQ0MKZ50Q6';
UPDATE events SET question='Will the margin of victory for Democrats in the New Hampshire''s 1st District House election be at least 4 percentage points?' WHERE event_id='CM-EVT-ZDPT74JVZ1';
UPDATE events SET question='Will the margin of victory for Democrats in the Minnesota''s 2nd District House election be at least 13 percentage points?' WHERE event_id='CM-EVT-3YTF9WJQ37';
UPDATE events SET question='Will the margin of victory for Republicans in the Michigan''s 1st District House election be at least 13 percentage points?' WHERE event_id='CM-EVT-4CBP7NLS72';
UPDATE events SET question='Will the margin of victory for Ed Gallrein in the Kentucky''s 4th District House Primary  election be at least 6 percentage points?' WHERE event_id='CM-EVT-L9MF5VX0G2';
UPDATE events SET question='Will the margin of victory for Democrats in the Kansas''s 3rd District House election be at least 14 percentage points?' WHERE event_id='CM-EVT-V0LHDFSSG6';
UPDATE events SET question='Will the margin of victory for Republicans in the Indiana''s 5th District House election be at least 1 percentage points?' WHERE event_id='CM-EVT-S26P9Y15Q9';
UPDATE events SET question='Will the margin of victory for Democrats in the Illinois''s 1st District House election be at least 26 percentage points?' WHERE event_id='CM-EVT-MWRVLX7NY7';
UPDATE events SET question='Will the margin of victory for Republicans in the Georgia''s 3rd District House election be at least 23 percentage points?' WHERE event_id='CM-EVT-R82458X4M1';
UPDATE events SET question='Will the margin of victory for Democrats in the Florida''s 23rd District House election be at least 5 percentage points?' WHERE event_id='CM-EVT-MR777M63G5';
UPDATE events SET question='Will the margin of victory for Republicans in the Florida''s 2nd District House election be at least 4 percentage points?' WHERE event_id='CM-EVT-839RJSYTH2';
UPDATE events SET question='Will the margin of victory for Democrats in the Connecticut''s 5th District House election be at least 6 percentage points?' WHERE event_id='CM-EVT-84JR3RQKD8';
UPDATE events SET question='Will the margin of victory for Democrats in the Connecticut''s 1st District House election be at least 22 percentage points?' WHERE event_id='CM-EVT-92PYSZMSS2';
UPDATE events SET question='Will the margin of victory for Xavier Becerra in the governor primary election in California be at least 1 percentage points?' WHERE event_id='CM-EVT-FXN0YK6LH6';
UPDATE events SET question='Will the margin of victory for Republicans in the Arizona''s 9th District House election be at least 15 percentage points?' WHERE event_id='CM-EVT-1J6SZ25048';
UPDATE events SET question='Will the margin of victory for Democrats in the Arizona''s 3rd District House election be at least 39 percentage points?' WHERE event_id='CM-EVT-4YJHDPBPY7';
UPDATE events SET question='Will the margin of victory for Republicans in the Arizona''s 1st District House election be at least 1 percentage points?' WHERE event_id='CM-EVT-LCNQT9TY43';
UPDATE events SET question='Will the margin of victory for Republicans in the Arkansas''s 3rd District House election be at least 19 percentage points?' WHERE event_id='CM-EVT-BL6HFHK4H3';
UPDATE events SET question='Will the margin of victory for Republicans in the Alabama''s 5th District House election be at least 16 percentage points?' WHERE event_id='CM-EVT-R2MV5Q4NR4';
UPDATE events SET question='Will James Fishback finish 2nd in the 2026 Florida gubernatorial primary?' WHERE event_id='CM-EVT-3CCRHR07J9';
UPDATE events SET question='Will the margin of victory for Graham Platner in the 2026 Maine Democratic Senate primary be above 50%?' WHERE event_id='CM-EVT-09QF876RS2';
UPDATE events SET question='Will Spencer Pratt receive at least 30% of the popular vote in the first round of the 2026 Los Angeles mayoral election?' WHERE event_id='CM-EVT-S8923QMNC8';
UPDATE events SET question='Will Xavier Becerra finish 1st in the 2026 California Governor primary election?' WHERE event_id='CM-EVT-48HJ1FZ7T9';
UPDATE events SET question='Will the margin of victory for Ken Paxton in the 2026 Texas Republican Senate runoff be between 20% and 100%?' WHERE event_id='CM-EVT-WDW9695BR8';
UPDATE events SET question='Will Daniel Cameron receive between 30% and 35% of the popular vote in the 2026 Kentucky Republican U.S. Senate primary?' WHERE event_id='CM-EVT-VZ8T85CZQ5';
UPDATE events SET question='Will Barry Moore receive between 35% and 40% of the popular vote in the first round of the 2026 Alabama Republican U.S. Senate primary?' WHERE event_id='CM-EVT-QKDXWLNLS6';
UPDATE events SET question='Will Sharif Street receive between 25% and 30% of the popular vote in the 2026 Pennsylvania 3rd Congressional District Democratic primary?' WHERE event_id='CM-EVT-QTK099NG95';
UPDATE events SET question='Will Ala Stanford receive between 20% and 25% of the popular vote in the 2026 Pennsylvania 3rd Congressional District Democratic primary?' WHERE event_id='CM-EVT-0KS4MHKP18';
UPDATE events SET question='Will Ed Gallrein receive between 54% and 57% of the popular vote in the 2026 Kentucky 4th Congressional District Republican primary?' WHERE event_id='CM-EVT-06J5GZHCP8';
UPDATE events SET question='Will Ed Diehl receive between 30% and 35% of the popular vote in the 2026 Oregon Republican gubernatorial primary?' WHERE event_id='CM-EVT-B8M2V9V998';
UPDATE events SET question='Will Derek Dooley finish 2nd in the first round of the Georgia Republican Senate primary?' WHERE event_id='CM-EVT-W9WJT35WX7';
UPDATE events SET question='Will Jared Hudson finish 2nd in the first round of the 2026 Alabama Republican U.S. Senate primary?' WHERE event_id='CM-EVT-1QJ6VWGG39';
UPDATE events SET question='Will Sharif Street finish 2nd in the 2026 Pennsylvania 3rd Congressional District Democratic primary?' WHERE event_id='CM-EVT-RJM0Q2TN30';
UPDATE events SET question='Will Jason Esteves finish 2nd in the first round of the 2026 Georgia Democratic gubernatorial primary?' WHERE event_id='CM-EVT-CZ1WWX1GR2';
UPDATE events SET question='Will the margin of victory for Ed Gallrein in the 2026 KY-04 Republican primary be between 5% and 10%?' WHERE event_id='CM-EVT-FH6177M0Y7';
UPDATE events SET question='Will the margin of victory for Keisha Lance Bottoms in the first round of the 2026 Democratic gubernatorial primary be above 25%?' WHERE event_id='CM-EVT-FL7T62FQY5';
UPDATE events SET question='Will the margin of victory for Houston Gaines in the first round of the 2026 Georgia 10th Congressional District Republican primary be above 25%?' WHERE event_id='CM-EVT-PM7ZZ1DKQ9';
UPDATE events SET question='Will Democrats win exactly 1 seats in the 2026 U.S. House of Representatives elections in South Carolina?' WHERE event_id='CM-EVT-7066ZJ80D5';
UPDATE events SET question='Will the margin of victory for Spencer Pratt in the first round of the 2026 Los Angeles mayoral election be above 0%?' WHERE event_id='CM-EVT-D63V66YZ42';
UPDATE events SET question='Will Mette Frederiksen become Prime Minister of Denmark following the 2026 Danish general election?' WHERE event_id='CM-EVT-Z70N8FWD96';
UPDATE events SET question='Will the Republican Party win 193 seats  in the 120th Congress?' WHERE event_id='CM-EVT-F825SK9C87';
UPDATE events SET question='Will the Democratic Party hold more than 52 seats in the 120th Congress?' WHERE event_id='CM-EVT-2D3LD0RMN9';
UPDATE events SET question='Will the Democratic party win the governorship in Pennsylvania' WHERE event_id='CM-EVT-05XLLSTC09';
UPDATE events SET question='Will the Democratic party win the governorship in Illinois' WHERE event_id='CM-EVT-Z8JF0KZ5G3';
UPDATE events SET question='Will the Republican party win the governorship in Georgia' WHERE event_id='CM-EVT-RHX55RJPT1';
UPDATE events SET question='State of the economy at the end of 2026?' WHERE event_id='CM-EVT-ZRG5DFDMZ8';
UPDATE events SET question='Will Tulsi Gabbard leaves Director of National Intelligence (DNI) before Aug 1, 2026?' WHERE event_id='CM-EVT-ZFQ2GS38V2';
UPDATE events SET question='Will it be reported by any of the Source Agencies that a Summary of Economic Projections omits individual participants’ federal-funds-rate projections before Jan 1, 2027?' WHERE event_id='CM-EVT-VB6B4LJ482';
UPDATE events SET question='Will the Democratic party win the Attorney General race in Wisconsin?' WHERE event_id='CM-EVT-2QLB6774D8';
UPDATE events SET question='Who will be the next Secretary-General of UN?' WHERE event_id='CM-EVT-Y26HBBBK98';
UPDATE events SET question='Will Democratic win the House race for WA-01?' WHERE event_id='CM-EVT-JQDVFMMKW1';
UPDATE events SET question='Will Democratic win the House race for VA-08?' WHERE event_id='CM-EVT-R7TF4JF089';
UPDATE events SET question='Will Republican win the House race for VA-05?' WHERE event_id='CM-EVT-J5Q1GQ0MF2';
UPDATE events SET question='Will Republican win the House race for TX-23?' WHERE event_id='CM-EVT-YH1CQHVXR0';
UPDATE events SET question='Will Republican win the House race for TX-13?' WHERE event_id='CM-EVT-F8TPPH5536';
UPDATE events SET question='Will Republican win the House race for TN-03?' WHERE event_id='CM-EVT-SJSPWL4F18';
UPDATE events SET question='Will Republican win the House race for SC-07?' WHERE event_id='CM-EVT-VXTXX4B3Y1';
UPDATE events SET question='Will Republican win the House race for SC-02?' WHERE event_id='CM-EVT-J187LB3C48';
UPDATE events SET question='Will Republican win the House race for PA-15?' WHERE event_id='CM-EVT-R106YX68Z1';
UPDATE events SET question='Will Republican win the House race for NV-02?' WHERE event_id='CM-EVT-MKTKFVXDZ7';
UPDATE events SET question='Will Democratic win the House race for NJ-12?' WHERE event_id='CM-EVT-TQYYZXLNH6';
UPDATE events SET question='Will Republican win the House race for NJ-02?' WHERE event_id='CM-EVT-PLPDDX9JC8';
UPDATE events SET question='Will Democratic win the House race for MN-05?' WHERE event_id='CM-EVT-1F7LPV1P19';
UPDATE events SET question='Will Republican win the House race for MN-01?' WHERE event_id='CM-EVT-0HH4XXLY85';
UPDATE events SET question='Will Republican win the House race for MI-02?' WHERE event_id='CM-EVT-07VVH6KW59';
UPDATE events SET question='Will Republican win the House race for MI-01?' WHERE event_id='CM-EVT-GGHBXQVB54';
UPDATE events SET question='Will Republican win the House race for LA-06?' WHERE event_id='CM-EVT-1Y611FWM07';
UPDATE events SET question='Will Republican win the House race for LA-05?' WHERE event_id='CM-EVT-JH00NBV4W8';
UPDATE events SET question='Will Republican win the House race for FL-09?' WHERE event_id='CM-EVT-DZ1HCD1GF9';
UPDATE events SET question='Will Democratic win the House race for CA-33?' WHERE event_id='CM-EVT-DZBB2QLC94';
UPDATE events SET question='Will Democratic win the House race for AL-02?' WHERE event_id='CM-EVT-VNGYPPDNV9';
UPDATE events SET question='Will Republicans win the Senate race in South Carolina?' WHERE event_id='CM-EVT-YB0M8XXMW8';
UPDATE events SET question='Will Democratics win the Senate race in New Mexico?' WHERE event_id='CM-EVT-ZD0C3KWW30';
UPDATE events SET question='Will Democratics win the Senate race in New Jersey?' WHERE event_id='CM-EVT-K0XGT91X91';
UPDATE events SET question='Will Democratics win the Senate race in New Hampshire?' WHERE event_id='CM-EVT-NF2DF1TXH9';
UPDATE events SET question='Will Democratic (DFL)s win the Senate race in Minnesota?' WHERE event_id='CM-EVT-M1PTCWQCS1';
UPDATE events SET question='Will Republicans win the Senate race in Idaho?' WHERE event_id='CM-EVT-TRRJX6C1D5';
UPDATE events SET question='Will Democratics win the Senate race in Georgia?' WHERE event_id='CM-EVT-1S96Y2D1N4';
UPDATE events SET question='Will Republicans win the Senate race in Florida?' WHERE event_id='CM-EVT-RH8TYT65S0';
UPDATE events SET question='Will Democratic win the House race for NC-11?' WHERE event_id='CM-EVT-0N8GC3M3K5';
UPDATE events SET question='Will Republican win the House race for MO-05?' WHERE event_id='CM-EVT-9K8QCZYSH5';
UPDATE events SET question='Will a Democrat win the House race for WI-3?' WHERE event_id='CM-EVT-6C7CNWJ6R7';
UPDATE events SET question='Will Democratic win the House race for VA-1?' WHERE event_id='CM-EVT-HN8Q6236V8';
UPDATE events SET question='Will Democratic win the House race for PA-8?' WHERE event_id='CM-EVT-RB6J9TCV17';
UPDATE events SET question='Will Democratic win the House race for PA-7?' WHERE event_id='CM-EVT-6S7C40J637';
UPDATE events SET question='Will Democratic win the House race for NJ-7?' WHERE event_id='CM-EVT-P0428D3JR9';
UPDATE events SET question='Will Republican win the House race for ME-2?' WHERE event_id='CM-EVT-JWBGQF2D62';
UPDATE events SET question='Will Democratic win the House race for IA-3?' WHERE event_id='CM-EVT-2VB36981K2';
UPDATE events SET question='Will Republican win the House race for CO-3?' WHERE event_id='CM-EVT-B6TYC4DNV3';
UPDATE events SET question='Will Republican win the House race for CA-40?' WHERE event_id='CM-EVT-6ZKKZ8ZKF8';
UPDATE events SET question='Will Democratic win the House race for CA-3?' WHERE event_id='CM-EVT-R46C4PCBV6';
UPDATE events SET question='Will Republican win the House race for AK-AL?' WHERE event_id='CM-EVT-97GCZBGWV8';
UPDATE events SET question='Will the Democratic party win the Attorney General race in New York?' WHERE event_id='CM-EVT-2WVDLYDTS5';
UPDATE events SET question='Will the Democratic party win the governorship in Arizona' WHERE event_id='CM-EVT-1CZBBW0SJ9';
UPDATE events SET question='Will Larry Page be one of the three wealthiest people in the world?' WHERE event_id='CM-EVT-CTGDGPT350';
UPDATE events SET question='Will the price of natural gas get below $2.60 per million BTU before January 1, 2027?' WHERE event_id='CM-EVT-YPZGNHXW59';
UPDATE events SET question='Will the price of natural gas get above $7.00 per million BTU before January 1, 2027?' WHERE event_id='CM-EVT-ZT1ML7KRX8';
UPDATE events SET question='Will Donald Trump meet in person Xi Jinping before Jan 1, 2027?' WHERE event_id='CM-EVT-WY1J5J92Q7';
UPDATE events SET question='Will legislation that would temporarily suspend or reduce the federal excise tax on gasoline become law before Jan 1, 2027?' WHERE event_id='CM-EVT-ZMQYC7K780';
UPDATE events SET question='Will Mandatory funding for ICE or CBP lasting at least 3 years be in the next reconciliation bill?' WHERE event_id='CM-EVT-1BY2QKWDX8';
UPDATE events SET question='Will Musk have a net worth more than 900 billion dollars before 2027?' WHERE event_id='CM-EVT-86RKRXH381';
UPDATE events SET question='Will Dem Nominee be Graham Platner AND General Election Winner be Democrat for Jan 2027?' WHERE event_id='CM-EVT-2KYR51YTD3';
UPDATE events SET question='Will the Israeli parliament be dissolved before Jun 30, 2026?' WHERE event_id='CM-EVT-W310M8M6V9';
UPDATE events SET question='Will legislation that funds ICE''s Enforcement and Removal Operations (ERO) become law before Jul 1, 2026?' WHERE event_id='CM-EVT-RJNYTQ9C61';
UPDATE events SET question='Will a bill become law taxing or banning hedge funds from owning homes before election day?' WHERE event_id='CM-EVT-HH1QMWSWC1';
UPDATE events SET question='When will FDA announce Reclassification of BPC-157 to Category 1 of the Bulk Drug Substances List?' WHERE event_id='CM-EVT-1BNKFN8JX3';
UPDATE events SET question='Will Iran hold a presidential election before Jan 1, 2027?' WHERE event_id='CM-EVT-247F6W3ZL0';
UPDATE events SET question='Will the Democratic party win the governorship in New York' WHERE event_id='CM-EVT-CJ3XX5L1P1';
UPDATE events SET question='Will the Democratic party win the governorship in New Mexico' WHERE event_id='CM-EVT-QTQW7NNPG8';
UPDATE events SET question='Will Miguel Díaz-Canel leave office before 2026-09-01T14:00:00.000Z?' WHERE event_id='CM-EVT-FTNVG3MMR2';
UPDATE events SET question='Will Tim Pool attend any White House press briefing which takes place in the James S. Brady Press Briefing Room?' WHERE event_id='CM-EVT-5ZZS438MW0';
UPDATE events SET question='Will S&P 500 Total Return Index outperform Gold?' WHERE event_id='CM-EVT-19C8FVK4P0';
UPDATE events SET question='Will the Nasdaq-100 be below 19000 at the end of Dec 31, 2026 at 4pm EST?' WHERE event_id='CM-EVT-JPWZDPJ339';
UPDATE events SET question='Will the S&P 500 be between 7600 and 7799.99 on Dec 31, 2026 at 4pm EST?' WHERE event_id='CM-EVT-K47V5LVKY9';
UPDATE events SET question='Who will win the next Gambian presidential election?' WHERE event_id='CM-EVT-QWL4XW2R90';
UPDATE events SET question='Will at least 5 the Senate Republicans lose re-election in 2026?' WHERE event_id='CM-EVT-39Y2BB24Y8';
UPDATE events SET question='UK Nominal GDP in 2026?' WHERE event_id='CM-EVT-1XDQZN2B72';
UPDATE events SET question='China Nominal GDP in 2026?' WHERE event_id='CM-EVT-SPVZJ1PGM2';
UPDATE events SET question='Who will win the Fields Medal in 2026?' WHERE event_id='CM-EVT-61DZDC02K1';
UPDATE events SET question='Will Apple announce a foldable phone by Dec 31, 2026?' WHERE event_id='CM-EVT-HKKK5BD3T1';
UPDATE events SET question='Who will win the governorship in Alaska?' WHERE event_id='CM-EVT-B206SG3QQ3';
UPDATE events SET question='Will Iliana Yotova win the 2026 Bulgarian presidential election?' WHERE event_id='CM-EVT-WVWY5FW7D3';
UPDATE events SET question='Will Cory Mills leave the House before the midterms?' WHERE event_id='CM-EVT-YD02QTFFS0';
UPDATE events SET question='Will Mary Peltola win the 2026 Alaska Senate race?' WHERE event_id='CM-EVT-6KJ40RJZP3';
UPDATE events SET question='Will Micah Lasher be the Democratic nominee for NY-12?' WHERE event_id='CM-EVT-54JFD3XF15';
UPDATE events SET question='Will Glenn Grothman be the Republican nominee for WI-06?' WHERE event_id='CM-EVT-7BMB4TXW22';
UPDATE events SET question='Will Sam Wong be the Republican nominee for VA-10?' WHERE event_id='CM-EVT-4Y6SNMQHK6';
UPDATE events SET question='Will Celeste Maloy be the Republican nominee for UT-03?' WHERE event_id='CM-EVT-YFQNF2DKR1';
UPDATE events SET question='Who will win the Minnesota State House?' WHERE event_id='CM-EVT-91GC6VJ3S0';
UPDATE events SET question='Will Abdul El-Sayed be the Democratic nominee for the Senate in Michigan?' WHERE event_id='CM-EVT-ZMWFMPNXD9';
UPDATE events SET question='Will Susan Collins be the Republican nominee for the Senate in Maine?' WHERE event_id='CM-EVT-FJC909J0Z4';
UPDATE events SET question='Will Graham Platner be the Democratic nominee for the Senate in Maine?' WHERE event_id='CM-EVT-G33KKHRDN4';
UPDATE events SET question='Will Ashley Moody be the Republican nominee for the Senate in Florida?' WHERE event_id='CM-EVT-YZ4P8Z2071';
UPDATE events SET question='Will Nikki Gronli be the Democratic nominee for SD-AL?' WHERE event_id='CM-EVT-TNXW9L8DV3';
UPDATE events SET question='Will Joe Wilson be the Republican nominee for SC-02?' WHERE event_id='CM-EVT-SB5KJHSH40';
UPDATE events SET question='Will Claire Valdez be the Democratic nominee for NY-07?' WHERE event_id='CM-EVT-RTX18RS8Z0';
UPDATE events SET question='Will Ritchie Torres be the Democratic nominee for NY-15?' WHERE event_id='CM-EVT-218DCWDP37';
UPDATE events SET question='Will David Flippo be the Republican nominee for NV-02?' WHERE event_id='CM-EVT-KQV1P38Q22';
UPDATE events SET question='Will Dina Titus be the Democratic nominee for NV-01?' WHERE event_id='CM-EVT-4DWTLXR4D3';
UPDATE events SET question='Will Adam Hamawy be the Democratic nominee for NJ-12?' WHERE event_id='CM-EVT-63WP9R3XT5';
UPDATE events SET question='Will Rosie Pino be the Republican nominee for NJ-09?' WHERE event_id='CM-EVT-HFHLD0DVD3';
UPDATE events SET question='Will Lily Tang Williams be the Republican nominee for NH-02?' WHERE event_id='CM-EVT-G4F0V1WH55';
UPDATE events SET question='Will Jason T Smith be the Republican nominee for MO-08?' WHERE event_id='CM-EVT-QJQ54Z4BP4';
UPDATE events SET question='Will Eric W Burlison be the Republican nominee for MO-07?' WHERE event_id='CM-EVT-T3BJFKZH87';
UPDATE events SET question='Will Mark Alford be the Republican nominee for MO-04?' WHERE event_id='CM-EVT-FRG4Q8TZ54';
UPDATE events SET question='Will Bob Onder be the Republican nominee for MO-03?' WHERE event_id='CM-EVT-G8TBP2F137';
UPDATE events SET question='Will Ann Wagner be the Republican nominee for MO-02?' WHERE event_id='CM-EVT-DZGJ87N6Y2';
UPDATE events SET question='Will Ilhan Omar be the Democratic nominee for MN-05?' WHERE event_id='CM-EVT-4DHF1BC231';
UPDATE events SET question='Will TP Nykoriak be the Republican nominee for MI-13?' WHERE event_id='CM-EVT-5WJXY1SQR5';
UPDATE events SET question='Will Eric Chung be the Democratic nominee for MI-10?' WHERE event_id='CM-EVT-D3VVN8D894';
UPDATE events SET question='Will Ben Ambrose be the Democratic nominee for MI-02?' WHERE event_id='CM-EVT-B6ZSBZZD57';
UPDATE events SET question='Will Bill Keating be the Democratic nominee for MA-09?' WHERE event_id='CM-EVT-TX96CWLT76';
UPDATE events SET question='Will Richard Neal be the Democratic nominee for MA-01?' WHERE event_id='CM-EVT-FVM9ZNZPY7';
UPDATE events SET question='Will Mariannette Miller-Meeks be the Republican nominee for IA-01?' WHERE event_id='CM-EVT-F49VMGR806';
UPDATE events SET question='Will Phil Scott be the Republican nominee for Governor in Vermont?' WHERE event_id='CM-EVT-4TTXGHY3W0';
UPDATE events SET question='Will Pamela Evette be the Republican nominee for Governor in South Carolina?' WHERE event_id='CM-EVT-S9QX4XH3Z3';
UPDATE events SET question='Will Deb Haaland be the Democratic nominee for Governor in New Mexico?' WHERE event_id='CM-EVT-LN0TW6V6L6';
UPDATE events SET question='Will David Jolly be the Democratic nominee for Governor in Florida?' WHERE event_id='CM-EVT-4H481CYQQ6';
UPDATE events SET question='Will Andy Biggs be the Republican nominee for Governor in Arizona?' WHERE event_id='CM-EVT-VP95P5VFT1';
UPDATE events SET question='Will Eliott Rodriguez be the Democratic nominee for FL-27?' WHERE event_id='CM-EVT-2NN6LKDWW9';
UPDATE events SET question='Will Sydney Gruters be the Republican nominee for FL-16?' WHERE event_id='CM-EVT-N3YVPG9KC0';
UPDATE events SET question='Will Anna Paulina Luna be the Republican nominee for FL-13?' WHERE event_id='CM-EVT-FZXLNDCLX8';
UPDATE events SET question='Will Leela Gray be the Democratic nominee for FL-13?' WHERE event_id='CM-EVT-M6W6B3GMY3';
UPDATE events SET question='Will Jim Norton be the Republican nominee for FL-02?' WHERE event_id='CM-EVT-G0W65LGFP8';
UPDATE events SET question='Will Maxine Waters place first in the 2026 CA-43 primary?' WHERE event_id='CM-EVT-F11N72F221';
UPDATE events SET question='Will Hilda Solis advance in the 2026 CA-38 primary?' WHERE event_id='CM-EVT-X4QM2G1R47';
UPDATE events SET question='Will Norma Torres place first in the 2026 CA-35 primary?' WHERE event_id='CM-EVT-13M83790Q2';
UPDATE events SET question='Will Laura Friedman advance in the 2026 CA-30 primary?' WHERE event_id='CM-EVT-DMT66K2B85';
UPDATE events SET question='Will Raul Ruiz place first in the 2026 CA-25 primary?' WHERE event_id='CM-EVT-PRT5FXGY53';
UPDATE events SET question='Will Sam Liccardo place first in the 2026 CA-16 primary?' WHERE event_id='CM-EVT-1DCDJXFR39';
UPDATE events SET question='Will Scott Wiener place first in the 2026 CA-11 primary?' WHERE event_id='CM-EVT-DWVZ5TGXF0';
UPDATE events SET question='Will Doris Matsui place first in the 2026 CA-07 primary?' WHERE event_id='CM-EVT-2X2DB8ZWT4';
UPDATE events SET question='Will Tom McClintock place first in the 2026 CA-05 primary?' WHERE event_id='CM-EVT-PM472603C3';
UPDATE events SET question='Who will win the 2026 CA-11 primary?' WHERE event_id='CM-EVT-CS1LLBDNJ0';
UPDATE events SET question='Who will win the CA-11 House election?' WHERE event_id='CM-EVT-2BF5TFGQJ0';
UPDATE events SET question='Will Bernadette Greene Placentia be the Democratic nominee for AZ-08?' WHERE event_id='CM-EVT-ZWR7LQF932';
UPDATE events SET question='Will Greg Stanton be the Democratic nominee for AZ-04?' WHERE event_id='CM-EVT-QF3YQZRMN1';
UPDATE events SET question='Will the upper bound of the federal funds rate be above 3.50% following the Fed''s Oct 28, 2026 meeting?' WHERE event_id='CM-EVT-6BS28TS762';
UPDATE events SET question='Who will win the next Israeli legislative election?' WHERE event_id='CM-EVT-DHTJ7K1463';
UPDATE events SET question='Will Ken Sim win the 2026 Vancouver mayoral election?' WHERE event_id='CM-EVT-MSVDFZBF29';
UPDATE events SET question='Will Tarcísio de Freitas win the 2026 São Paulo gubernatorial election?' WHERE event_id='CM-EVT-Q4TP116VW3';
UPDATE events SET question='Will Luiz Inácio Lula da Silva be on the ballot in the next Brazilian presidential election?' WHERE event_id='CM-EVT-GZ95QDFPN6';
UPDATE events SET question='Will Liberal Party win the 2026 Brazilian Senate election?' WHERE event_id='CM-EVT-ZRRTJHQJ11';
UPDATE events SET question='Will Ed Markey be the Democratic nominee for the Senate in Massachusetts?' WHERE event_id='CM-EVT-J620PJQLH6';
UPDATE events SET question='Will Jack Reed be the Democratic nominee for the Senate in Rhode Island?' WHERE event_id='CM-EVT-R4TV1VBQH2';
UPDATE events SET question='Who will win Alaska''s top-four primary for Governor?' WHERE event_id='CM-EVT-D03FJ4YFW7';
UPDATE events SET question='Will Mark Lamb be the Republican nominee for AZ-5?' WHERE event_id='CM-EVT-8CT1HTT0M9';
UPDATE events SET question='Will James Fishback receive at least 20% of the popular vote in the 2026 Florida Republican Senate primary?' WHERE event_id='CM-EVT-3BTF9D60C9';
UPDATE events SET question='Will Randy Fine be the Republican nominee for FL-06?' WHERE event_id='CM-EVT-JM46D114M2';
UPDATE events SET question='Will Candace Owens endorse James Fishback in Florida''s gubernatorial election (primary or general) before Aug 18, 2026?' WHERE event_id='CM-EVT-YP9NSQG7K3';
UPDATE events SET question='Will Michele Tafoya be the Republican nominee for the Senate in Minnesota?' WHERE event_id='CM-EVT-Z7R0P6BLG9';
UPDATE events SET question='Will Matt Little be the Democratic (DFL) nominee for MN-2?' WHERE event_id='CM-EVT-N7Y000CV81';
UPDATE events SET question='Who will be the Republican nominee for Attorney General in Arizona?' WHERE event_id='CM-EVT-PDYT2QJPL6';
UPDATE events SET question='Will Jeremy Moss be the Democratic nominee for MI-11?' WHERE event_id='CM-EVT-YNSF3VR2R3';
UPDATE events SET question='CPI core year-over-year in Jun 2026?' WHERE event_id='CM-EVT-DKLJV3BYH6';
UPDATE events SET question='Will the rate of core CPI inflation be above 2.8% for the year ending in June 2026?' WHERE event_id='CM-EVT-B5KCGZG8C0';
UPDATE events SET question='Will Jeff Hurd be the Republican nominee for CO-03?' WHERE event_id='CM-EVT-J2BHMCY596';
UPDATE events SET question='Will the tariff rate on China imports be between 10% and 19.99% on Jul 1, 2026?' WHERE event_id='CM-EVT-0F3FPFL7B8';
UPDATE events SET question='Will the tariff rate on India imports be between 10% and 19.99% on Jul 1, 2026?' WHERE event_id='CM-EVT-FC5Z7GXWS9';
UPDATE events SET question='Will the tariff rate on the European Union imports be between 10% and 19.99% on Jul 1, 2026?' WHERE event_id='CM-EVT-1QBQ53ZQW2';
UPDATE events SET question='Will John Hickenlooper be the Democratic nominee for the Senate in Colorado?' WHERE event_id='CM-EVT-2HW5SFCPP9';
UPDATE events SET question='Will Darializa Avila Chevalier be the Democratic nominee for NY-13?' WHERE event_id='CM-EVT-MZHDBYNN72';
UPDATE events SET question='Will Gregg Hull be the Republican nominee for Governor in New Mexico?' WHERE event_id='CM-EVT-BB96NTRXS5';
UPDATE events SET question='Will Kevin Hern be the Republican nominee for the Senate in Oklahoma?' WHERE event_id='CM-EVT-GT3MGFQY76';
UPDATE events SET question='Will the 7-day moving average of transit calls through the Strait of Hormuz as reported by the IMF PortWatch be above 60 before July 1, 2026?' WHERE event_id='CM-EVT-78FY38Z4R5';
UPDATE events SET question='Will Alex Zdan be the Republican nominee for the Senate in New Jersey?' WHERE event_id='CM-EVT-D63F4PXC53';
UPDATE events SET question='Will Elon Musk''s net worth for May be above $675 billion?' WHERE event_id='CM-EVT-YS54TDB896';
UPDATE events SET question='Will 30Y US Treasury Yield before month-end be above 5.15%?' WHERE event_id='CM-EVT-TTJHVWZ2H1';
UPDATE events SET question='Will Steve Hilton receive between 20% and 24% of the popular vote in the 2026 California gubernatorial primary?' WHERE event_id='CM-EVT-82FXFQ2GW9';
UPDATE events SET question='Will Eric Swalwell receive between 0% and 4% of the popular vote in the 2026 California gubernatorial primary?' WHERE event_id='CM-EVT-5F3B820YW7';
UPDATE events SET question='Will Alani Bankhead be the Democratic nominee for the Senate in Montana?' WHERE event_id='CM-EVT-FCBJG9YGF9';
UPDATE events SET question='Will Robert Menendez Jr. be the Democratic nominee for NJ-08?' WHERE event_id='CM-EVT-8PFZ2XGQD0';
UPDATE events SET question='Will Josh Turek be the Democratic nominee for the Senate in Iowa?' WHERE event_id='CM-EVT-F12MPVGGW7';
UPDATE events SET question='Donald Trump and Jensen Huang meet before Jun 1, 2026?' WHERE event_id='CM-EVT-5NYWZN1GS0';
UPDATE events SET question='Will the Election Postponed Beyond Expiration win the next Lebanese general election?' WHERE event_id='CM-EVT-5P267Q2WW9';
UPDATE events SET question='Will Iván Cepeda Castro win the first round of the 2026 Colombian presidential election?' WHERE event_id='CM-EVT-XMJLWR99Z9';
UPDATE events SET question='Will Abelardo de la Espriella win the next Colombian presidential election?' WHERE event_id='CM-EVT-XXLPNHG7J7';
UPDATE events SET question='SOL price  on May 29, 2026?' WHERE event_id='CM-EVT-MQCM8V7LZ0';
UPDATE events SET question='Ethereum price at May 29, 2026 at 5pm EDT?' WHERE event_id='CM-EVT-GH94RM52P2';
UPDATE events SET question='Dogecoin price  on May 29, 2026?' WHERE event_id='CM-EVT-GR9RS68QW6';
UPDATE events SET question='Will the maximum SP500 value reach 7500 by May 29, 2026?' WHERE event_id='CM-EVT-016Z206N61';
UPDATE events SET question='Will the **high temp in LA** be 68-69° on May 27, 2026?' WHERE event_id='CM-EVT-Z9TBQBV7V5';
UPDATE events SET question='Will the Nasdaq-100 be above 29899.99 at the end of May 27, 2026 at 4pm EDT?' WHERE event_id='CM-EVT-8W89HNJVQ1';
UPDATE events SET question='Will the S&P 500 be above 7499.9999 on May 27, 2026 at 4pm EDT?' WHERE event_id='CM-EVT-HMJ9TY5QY9';
UPDATE events SET question='Ethereum price at May 27, 2026 at 5pm EDT?' WHERE event_id='CM-EVT-LZ41DQB401';
UPDATE events SET question='Bitcoin price  on May 27, 2026?' WHERE event_id='CM-EVT-R95S7G87T2';
UPDATE events SET question='Bitcoin price  on May 27, 2026?' WHERE event_id='CM-EVT-455Y0HQ123';
UPDATE events SET question='Will the S&P 500 be above 7494.9999 on May 27, 2026 at 3pm EDT?' WHERE event_id='CM-EVT-03M3NDMR10';
UPDATE events SET question='Will Ken Paxton win Dallas County?' WHERE event_id='CM-EVT-RBF032VBB7';
UPDATE events SET question='Will Barry Moore be the Republican nominee for the Senate in Alabama?' WHERE event_id='CM-EVT-CGXRBP5B57';
UPDATE events SET question='Will John F. Kennedy be the Republican nominee for Lt. Governor in Georgia?' WHERE event_id='CM-EVT-YC37G79XT3';
UPDATE events SET question='Will Rob Adkerson be the Republican nominee for GA-11?' WHERE event_id='CM-EVT-PVSZ03C2W4';
UPDATE events SET question='Will it be reported that the United States Department of State issues one or more United States passports to U.S. citizens where the passport contains an image or visual representation of Donald Trump’s face before Aug 1, 2026?' WHERE event_id='CM-EVT-V9X0KCKYZ7';
UPDATE events SET question='Who will win 2026 Indiana Secretary of State Republican primary?' WHERE event_id='CM-EVT-J0Y1KGH4H1';
UPDATE events SET question='Will the Department of Justice (DOJ) release audio recordings of interviews conducted between Joe Biden and ghostwriter Marc Zwonitzer before Oct 1, 2026?' WHERE event_id='CM-EVT-K5WZ8F15F9';
UPDATE events SET question='Will Vivek Ramaswamy receive at least 80% of the popular vote in the 2026 Ohio Republican gubernatorial primary?' WHERE event_id='CM-EVT-QZH27R2WB8';
UPDATE events SET question='Will Casey Putsch receive between 15% and 18% of the popular vote in the 2026 Ohio Republican gubernatorial primary?' WHERE event_id='CM-EVT-2M98HRQZ86';
UPDATE events SET question='Will Eric Swalwell drop out of the California Governor primary before Jun 2, 2026?' WHERE event_id='CM-EVT-23BGQQPC61';
UPDATE events SET question='Will the Republican party win the governorship in Nebraska' WHERE event_id='CM-EVT-QH5FH3SNM6';
UPDATE events SET question='Will a crypto market structure bill becomes law before Jan 1, 2027?' WHERE event_id='CM-EVT-25SXVWH5D4';
UPDATE events SET question='MicroStrategy sells any Bitcoin in 2025?' WHERE event_id='CM-EVT-QW6P6GZ8N4';
UPDATE events SET question='Kraken IPO by March 31, 2026?' WHERE event_id='CM-EVT-9MQZ98PJT9';
UPDATE events SET question='Macron out in 2025?' WHERE event_id='CM-EVT-20RBBXSB30';
UPDATE events SET question='Ukraine recognizes Russian sovereignty over its territory by December 31, 2025?' WHERE event_id='CM-EVT-1L07BR8JD5';
UPDATE events SET question='Ukraine election called in 2025?' WHERE event_id='CM-EVT-QK40SMGDC3';
UPDATE events SET question='Will any country leave NATO by June 30, 2026?' WHERE event_id='CM-EVT-G0HQ1F72M3';
UPDATE events SET question='Mike Johnson out as Speaker by December 31?' WHERE event_id='CM-EVT-7599758YL7';
UPDATE events SET question='US x Russia military clash by December 31?' WHERE event_id='CM-EVT-207L4994P4';
UPDATE events SET question='Trump eliminates capital gains tax on crypto in 2025?' WHERE event_id='CM-EVT-YV6C06NTY2';
UPDATE events SET question='Will Russia capture Sumy before October?' WHERE event_id='CM-EVT-8C7H3KYMH4';
UPDATE events SET question='Will Pump.fun perform an airdrop by July 31?' WHERE event_id='CM-EVT-F9ZR807B11';
UPDATE events SET question='Will Hyperliquid perform an airdrop by December 31?' WHERE event_id='CM-EVT-1ZFN2MH7P8';
UPDATE events SET question='Will MegaETH perform an airdrop by June 30?' WHERE event_id='CM-EVT-W92LK6Z010';
UPDATE events SET question='Jeffrey Epstein foul play confirmed by December 31, 2026?' WHERE event_id='CM-EVT-FS93QYYZ65';
UPDATE events SET question='SCOTUS accepts sports event contract case by July 31, 2026?' WHERE event_id='CM-EVT-FLWXD81WN4';
UPDATE events SET question='Will Russia capture Lyman by December 31?' WHERE event_id='CM-EVT-GM6XLL63G6';
UPDATE events SET question='Netanyahu out by March 31?' WHERE event_id='CM-EVT-LTD4KR3MF4';
UPDATE events SET question='Will USDC hit 50% of USDT market cap by December 31, 2026?' WHERE event_id='CM-EVT-QZF44ZSYK3';
UPDATE events SET question='Will Hamas agree to disarm by December 31?' WHERE event_id='CM-EVT-NGWGHQ31H1';
UPDATE events SET question='Grok 5 released by December 31?' WHERE event_id='CM-EVT-6XZNH3J6M3';
UPDATE events SET question='U.S. x Russia Nuclear deal by December 31?' WHERE event_id='CM-EVT-1LKC5D42R3';
UPDATE events SET question='Will El Salvador hold $1b+ of BTC by December 31?' WHERE event_id='CM-EVT-HM4KZN3DX8';
UPDATE events SET question='Will Abstract launch a token by December 31, 2026' WHERE event_id='CM-EVT-0H1S6RH240';
UPDATE events SET question='Will Axiom launch a token by December 31, 2026?' WHERE event_id='CM-EVT-S8C9893HH2';
UPDATE events SET question='Will Unit launch a token in 2025?' WHERE event_id='CM-EVT-RFW6KCY9C6';
UPDATE events SET question='Israel strike on Damascus by March 31, 2026?' WHERE event_id='CM-EVT-Y7KHP4D735';
UPDATE events SET question='Israeli parliament dissolved by March 31?' WHERE event_id='CM-EVT-W69HG9C9G4';
UPDATE events SET question='Will Trump endorse John Cornyn for TX-Sen by Nov 2 2026 ET?' WHERE event_id='CM-EVT-HRDT88BKQ0';
UPDATE events SET question='Will Base launch a token in 2025?' WHERE event_id='CM-EVT-PZT6DFNS45';
UPDATE events SET question='Will Ostium launch a token by December 31, 2026?' WHERE event_id='CM-EVT-56FDWMH6L1';
UPDATE events SET question='Will Felix Protocol launch a token by December 31, 2026?' WHERE event_id='CM-EVT-42PYRCMVL3';
UPDATE events SET question='Will Abdul El-Sayed win the 2026 Michigan Democratic Primary?' WHERE event_id='CM-EVT-H7JM5BRSJ5';
UPDATE events SET question='Will Graham Platner be the Democratic nominee for Senate in Maine?' WHERE event_id='CM-EVT-2RT2G292H4';
UPDATE events SET question='Will Larry Ellison/Oracle acquire TikTok?' WHERE event_id='CM-EVT-G8JK3545S6';
UPDATE events SET question='Will MetaMask launch a token in 2025?' WHERE event_id='CM-EVT-TWHPMQF215';
UPDATE events SET question='Will Fannie Mae’s market cap be between $300B and $350B at market close on IPO day?' WHERE event_id='CM-EVT-73F27SY5L8';
UPDATE events SET question='Will Discord’s market cap be less than $15B at market close on IPO day?' WHERE event_id='CM-EVT-5DXJ7GQ789';
UPDATE events SET question='NATO x Russia military clash by June 30, 2026?' WHERE event_id='CM-EVT-0XQBBK1P10';
UPDATE events SET question='Israel x Hamas ceasefire cancelled by October 31?' WHERE event_id='CM-EVT-979N1H7345';
UPDATE events SET question='Will Tom Steyer win the California Governor Election in 2026?' WHERE event_id='CM-EVT-CXV3VJX3F4';
UPDATE events SET question='Will Spencer Pratt win the 2026 Los Angeles mayoral election?' WHERE event_id='CM-EVT-X47KV472H0';
UPDATE events SET question='Will the Republicans win the Maryland governor race in 2026?' WHERE event_id='CM-EVT-9PRWGGC5K1';
UPDATE events SET question='Will the Democrats win the New Mexico governor race in 2026?' WHERE event_id='CM-EVT-LVCZ70W4X1';
UPDATE events SET question='Will the Republicans win the New York governor race in 2026?' WHERE event_id='CM-EVT-Q2TMLJC0D5';
UPDATE events SET question='Will the Democrats win the Oregon governor race in 2026?' WHERE event_id='CM-EVT-082HQ0P413';
UPDATE events SET question='Will the Republicans win the Pennsylvania governor race in 2026?' WHERE event_id='CM-EVT-X8GH8VFYN1';
UPDATE events SET question='Will the Republicans win the South Carolina governor race in 2026?' WHERE event_id='CM-EVT-YY836SX827';
UPDATE events SET question='Will the Republicans win the Vermont governor race in 2026?' WHERE event_id='CM-EVT-R85JKZZ4R6';
UPDATE events SET question='Will prjx launch a token by December 31, 2026?' WHERE event_id='CM-EVT-M1DP2J4KL0';
UPDATE events SET question='Will the Republicans win the Idaho Senate race in 2026?' WHERE event_id='CM-EVT-HW8FT0L534';
UPDATE events SET question='Will DeepSeek have the second best AI model at the end of June 2026?' WHERE event_id='CM-EVT-HPPNCN88X2';
UPDATE events SET question='Lecornu  out as French PM by October 31?' WHERE event_id='CM-EVT-5YB5N8PF45';
UPDATE events SET question='Will Mary Peltola win the Alaska Senate race in 2026?' WHERE event_id='CM-EVT-FSS872PZ65';
UPDATE events SET question='Will Mary Peltola win the 2026 Alaska governor election?' WHERE event_id='CM-EVT-552YG8W5J1';
UPDATE events SET question='Will knots flip bitcoin core by December 31?' WHERE event_id='CM-EVT-DCGKL8Z594';
UPDATE events SET question='Claudia Sheinbaum out as President of Mexico by June 30?' WHERE event_id='CM-EVT-HTH44D6R59';
UPDATE events SET question='Will Jia Yueting enter mainland China by June 30?' WHERE event_id='CM-EVT-1THG91D108';
UPDATE events SET question='Will OpenAI IPO by December 31 2026?' WHERE event_id='CM-EVT-1J5WJ8DGM8';
UPDATE events SET question='Will Russia capture all of Kupiansk by December 31?' WHERE event_id='CM-EVT-FYD8DLYRM3';
UPDATE events SET question='Another S&P 500 Company buys Bitcoin by December 31, 2026?' WHERE event_id='CM-EVT-WJ156P6T41';
UPDATE events SET question='Will Russia capture all of Vovchansk by December 31?' WHERE event_id='CM-EVT-VGLC2HN3D1';
UPDATE events SET question='Will Hezbollah disarm by December 31?' WHERE event_id='CM-EVT-7GZ9MLR1T6';
UPDATE events SET question='Will US withdraw from NATO by April 30?' WHERE event_id='CM-EVT-MF2T04RSK7';
UPDATE events SET question='Will Trump deport 700-800k people?' WHERE event_id='CM-EVT-GL3LV3PND5';
UPDATE events SET question='Will Trump meet with Xi Jinping in 2026?' WHERE event_id='CM-EVT-D2FSS8S8N5';
UPDATE events SET question='Will Variational launch a token by December 31, 2026?' WHERE event_id='CM-EVT-0DS4GXJ3J7';
UPDATE events SET question='Will Spark launch a token by December 31?' WHERE event_id='CM-EVT-7BTSS5K9L9';
UPDATE events SET question='Israel and Indonesia normalize relations by June 30, 2026?' WHERE event_id='CM-EVT-ZZB2746L52';
UPDATE events SET question='Will Cho Kuk win the 2026 Busan Mayoral Election?' WHERE event_id='CM-EVT-8TT52LGH13';
UPDATE events SET question='U.S. Embassy in Damascus reopened by June 30, 2026?' WHERE event_id='CM-EVT-GCZ78T77M8';
UPDATE events SET question='Sudan civil war ceasefire in 2025?' WHERE event_id='CM-EVT-56LRJL3JK2';
UPDATE events SET question='Will Yoo Jeong-bok win the 2026 Incheon mayoral election?' WHERE event_id='CM-EVT-M7JM43V1F8';
UPDATE events SET question='Will Lee Chul-gyu win the 2026 Gangwon Province gubernatorial election?' WHERE event_id='CM-EVT-ZSLV13QFW4';
UPDATE events SET question='Will GMGN launch a token by December 31, 2025?' WHERE event_id='CM-EVT-SN81DFWXK0';
UPDATE events SET question='Will Extended launch a token by December 31 2025?' WHERE event_id='CM-EVT-84KNXK6W41';
UPDATE events SET question='Will Arc launch a token by March 31 2026?' WHERE event_id='CM-EVT-L197XLZMJ6';
UPDATE events SET question='Will Pacifica launch a token by March 31 2026?' WHERE event_id='CM-EVT-7DL8JP5X05';
UPDATE events SET question='AI bubble burst in 2026?' WHERE event_id='CM-EVT-KKQ4XW7FY4';
UPDATE events SET question='Russia x Ukraine Peace Parlay' WHERE event_id='CM-EVT-66S3LD3901';
UPDATE events SET question='Will Russia enter Orikhiv by March 31?' WHERE event_id='CM-EVT-1GXR0H97W4';
UPDATE events SET question='Will Ventuals launch a token by March 31 2026?' WHERE event_id='CM-EVT-7YTXFXFTH3';
UPDATE events SET question='Will Zelenskyy talk to Putin by March 31?' WHERE event_id='CM-EVT-CV6T08PD65';
UPDATE events SET question='Will Bitcoin reach $250,000 by December 31, 2026?' WHERE event_id='CM-EVT-2S263KKBP2';
UPDATE events SET question='Labour leadership election scheduled by March 31?' WHERE event_id='CM-EVT-TWP2W47YD4';
UPDATE events SET question='Will the US confirm that aliens exist before 2027?' WHERE event_id='CM-EVT-BSCL3ZK4F0';
UPDATE events SET question='Will Christina Henderson win the 2026 Democratic D.C. Mayoral Primary?' WHERE event_id='CM-EVT-BYQPD16TQ8';
UPDATE events SET question='Will Kristen Gonzalez be the Democratic nominee for NY-07?' WHERE event_id='CM-EVT-G8DDZ76CC1';
UPDATE events SET question='Will Tempo launch a token by June 30, 2026?' WHERE event_id='CM-EVT-TMVD0T7576';
UPDATE events SET question='Will Russia enter Borova by March 31?' WHERE event_id='CM-EVT-VHP385D1T6';
UPDATE events SET question='Will Theo launch a token by March 31 2026?' WHERE event_id='CM-EVT-RZLRZJ80V4';
UPDATE events SET question='Will Solstice launch a token by June 30 2026?' WHERE event_id='CM-EVT-SFL04DY404';
UPDATE events SET question='Ukraine officially agrees to a US backed ceasefire framework by December 31?' WHERE event_id='CM-EVT-VDGNRYZS97';
UPDATE events SET question='Will Fomo launch a token by June 30 2026?' WHERE event_id='CM-EVT-C6T8ZF4Z96';
UPDATE events SET question='Will Jared Moskowitz be the Democratic nominee for Senate in Florida?' WHERE event_id='CM-EVT-CS6SQN76R3';
UPDATE events SET question='Pedro Sánchez out as PM of Spain by June 30, 2026?' WHERE event_id='CM-EVT-1HSNRBYJ42';
UPDATE events SET question='Microstrategy delisted from MSCI index by March 31?' WHERE event_id='CM-EVT-PFG18CWL70';
UPDATE events SET question='Will Cinde Warmington win the 2026 New Hampshire Governor Democratic primary election?' WHERE event_id='CM-EVT-HW26MDK503';
UPDATE events SET question='Will Arya Azma win the 2026 Oklahoma Governor Democratic primary election?' WHERE event_id='CM-EVT-0D2Q11FF15';
UPDATE events SET question='Will Russia enter Dobropillia by January 31?' WHERE event_id='CM-EVT-DCMKC7Y6X0';
UPDATE events SET question='Will Douglas Moylan win the 2026 Guam Governor Republican primary election?' WHERE event_id='CM-EVT-LJBFXNQ4K8';
UPDATE events SET question='Will the number of Republican House members who retire in 2026 be between 28 and 31 inclusive?' WHERE event_id='CM-EVT-QWRCCPDWP5';
UPDATE events SET question='Will the Republican Party hold between 220 and 224 House seats after the 2026 midterm elections?' WHERE event_id='CM-EVT-HZZP4JMQ30';
UPDATE events SET question='Will Bitmine announce that it holds more than 7M ETH before 2027?' WHERE event_id='CM-EVT-DBFCWG8FL6';
UPDATE events SET question='Will the average monthly Ethereum gas price hit 20 Gwei before 2027?' WHERE event_id='CM-EVT-6SJC52SQ44';
UPDATE events SET question='Will the US officially declare war on Venezuela in 2025?' WHERE event_id='CM-EVT-H7S14HGB00';
UPDATE events SET question='Will the Democratic Party win the NE-02 House seat?' WHERE event_id='CM-EVT-ZY5PGRFV67';
UPDATE events SET question='Will the Republican Party win the NM-02 House seat?' WHERE event_id='CM-EVT-DB1RWJX7B4';
UPDATE events SET question='Will the Democratic Party win the NY-18 House seat?' WHERE event_id='CM-EVT-BB25KG8WN3';
UPDATE events SET question='Will Daylight launch a token by September 30, 2026?' WHERE event_id='CM-EVT-JSMK5Z6XB5';
UPDATE events SET question='Will the Republican Party win the TX-32 House seat?' WHERE event_id='CM-EVT-LLQWL3MH88';
UPDATE events SET question='Bitcoin all time high by March 31, 2026?' WHERE event_id='CM-EVT-7XKCKHYQX4';
UPDATE events SET question='Fed rate cut by January 2026 meeting?' WHERE event_id='CM-EVT-6WY59L0G19';
UPDATE events SET question='Ethereum all time high by March 31, 2026?' WHERE event_id='CM-EVT-25F0GNC1P7';
UPDATE events SET question='Solana all time high by June 30, 2026?' WHERE event_id='CM-EVT-4PF8HK6P16';
UPDATE events SET question='Will Tyler Kistner be the Republican Nominee for MN-02?' WHERE event_id='CM-EVT-34B0PNY4K8';
UPDATE events SET question='Ukraine peace referendum scheduled by June 30?' WHERE event_id='CM-EVT-S0SN3369D1';
UPDATE events SET question='Will Gold (GC) settle at $5,800-$6,200 in June?' WHERE event_id='CM-EVT-W8SF1QWYB1';
UPDATE events SET question='Will Crude Oil (CL) settle at >$84 in June?' WHERE event_id='CM-EVT-GH0WD1DXJ5';
UPDATE events SET question='Will Crude Oil (CL) hit (HIGH) $200 by end of June?' WHERE event_id='CM-EVT-648V1NDKW1';
UPDATE events SET question='Will Perena launch a token by June 30, 2026?' WHERE event_id='CM-EVT-3SFZVNYTK7';
UPDATE events SET question='EU/NATO country announces peacekeeping force in Ukraine by June 30?' WHERE event_id='CM-EVT-5VYX642RK0';
UPDATE events SET question='Thailand strikes Cambodia by January 31, 2026?' WHERE event_id='CM-EVT-33LV7DM5R6';
UPDATE events SET question='Will Russia capture all of Stepnohirsk by January 31, 2026?' WHERE event_id='CM-EVT-L5PSSDLBG6';
UPDATE events SET question='Will Reza Pahlavi enter Iran by March 31?' WHERE event_id='CM-EVT-JH2ZT7R9L5';
UPDATE events SET question='Will Russia capture all of Donetsk Oblast by June 30, 2026?' WHERE event_id='CM-EVT-00P074X336';
UPDATE events SET question='US forces in Venezuela again by January 31, 2026?' WHERE event_id='CM-EVT-L38GX1VTW0';
UPDATE events SET question='Will Nicolás Maduro be sentenced to no prison time?' WHERE event_id='CM-EVT-DYN1XGWYT5';
UPDATE events SET question='Will Milady floor price reach 2 ETH before 2027?' WHERE event_id='CM-EVT-B3R0Q3VK82';
UPDATE events SET question='Gustavo Petro out as leader of Colombia by June 30?' WHERE event_id='CM-EVT-9F02RZ6C04';
UPDATE events SET question='US strike on Mexico by March 31?' WHERE event_id='CM-EVT-WCK211J094';
UPDATE events SET question='US strike on Cuba by December 31?' WHERE event_id='CM-EVT-BF5TXDDWX0';
UPDATE events SET question='Delcy Rodríguez out as leader of Venezuela by January 31, 2026?' WHERE event_id='CM-EVT-BZWSRKRKD3';
UPDATE events SET question='Jerome Powell out from Fed Board by May 30?' WHERE event_id='CM-EVT-J8T6DYCJB3';
UPDATE events SET question='Will Perplexity not IPO by December 31, 2027?' WHERE event_id='CM-EVT-WF61RSVLN8';
UPDATE events SET question='Mahmoud Abbas out as Palestinian President by June 30?' WHERE event_id='CM-EVT-3641XVMNW4';
UPDATE events SET question='Insurrection Act invoked by January 31?' WHERE event_id='CM-EVT-CZP41RXMV3';
UPDATE events SET question='Israel strike on Yemen by March 31, 2026?' WHERE event_id='CM-EVT-C85G7616S2';
UPDATE events SET question='Will Lebanese Forces win the most seats in the 2026 Lebanese parliamentary election?' WHERE event_id='CM-EVT-XD933GFNK9';
UPDATE events SET question='Masoud Pezeshkian out by March 31?' WHERE event_id='CM-EVT-9HV2LCD070';
UPDATE events SET question='Will the upper bound of the target federal funds rate be ≥ 4.5% at the end of 2026?' WHERE event_id='CM-EVT-WB85BV4T72';
UPDATE events SET question='Will the US officially declare war on Iran by March 31, 2026?' WHERE event_id='CM-EVT-682DDGTXH2';
UPDATE events SET question='Taiwanese Premier Cho Jung-tai out by June 30, 2026?' WHERE event_id='CM-EVT-H5ZPNZ8HB4';
UPDATE events SET question='Will Russia enter Malokaterynivka by February 28, 2026?' WHERE event_id='CM-EVT-J735KSTG23';
UPDATE events SET question='Kadyrov out as Head of the Chechen Republic by June 30, 2026?' WHERE event_id='CM-EVT-TNM3W7MHZ5';
UPDATE events SET question='Will Russia capture Bilytske by April 30, 2026?' WHERE event_id='CM-EVT-3S2CRPLFD7';
UPDATE events SET question='Will Jimmie Åkesson be the next Prime Minister of Sweden?' WHERE event_id='CM-EVT-ZZP9SJ1045';
UPDATE events SET question='Will Rick Rieder be confirmed as Fed Chair and will rates hit 2.5% or lower in 2026?' WHERE event_id='CM-EVT-783J2KBHQ0';
UPDATE events SET question='Will SpaceX IPO by May 31, 2026?' WHERE event_id='CM-EVT-WT6P6Z4739';
UPDATE events SET question='Will SpaceX''s market cap be greater than $2.0T at market close on IPO day?' WHERE event_id='CM-EVT-9JB7JSKYX6';
UPDATE events SET question='Will Google Gemini score at least 45% on the FrontierMath Benchmark?' WHERE event_id='CM-EVT-KD8TSMK2T9';
UPDATE events SET question='Will any OpenAI GPT model score at least 60% on the FrontierMath Exam?' WHERE event_id='CM-EVT-DBZ45FJPX9';
UPDATE events SET question='Will the Democratic Party win the AL-01 House seat?' WHERE event_id='CM-EVT-TPY718RZ93';
UPDATE events SET question='Will the Democratic Party win the AL-07 House seat?' WHERE event_id='CM-EVT-BXM8194BH4';
UPDATE events SET question='Will the Republican Party win the AR-04 House seat?' WHERE event_id='CM-EVT-4F5C120Q97';
UPDATE events SET question='Will the Democratic Party win the AZ-04 House seat?' WHERE event_id='CM-EVT-1C27MK3415';
UPDATE events SET question='Will the Republican Party win the AZ-05 House seat?' WHERE event_id='CM-EVT-Z3718NKFX7';
UPDATE events SET question='Will the Democratic Party win the CA-01 House seat?' WHERE event_id='CM-EVT-TD97721XP2';
UPDATE events SET question='Will the Democratic Party win the CA-03 House seat?' WHERE event_id='CM-EVT-G89DGR47Y0';
UPDATE events SET question='Will the Republican Party win the CA-08 House seat?' WHERE event_id='CM-EVT-0PCD66Q7H0';
UPDATE events SET question='Will the Democratic Party win the CA-10 House seat?' WHERE event_id='CM-EVT-03RZ8RGCP3';
UPDATE events SET question='Will the Democratic Party win the CA-12 House seat?' WHERE event_id='CM-EVT-T59489MHJ0';
UPDATE events SET question='Will the Republican Party win the CA-18 House seat?' WHERE event_id='CM-EVT-Q0B56HHYC3';
UPDATE events SET question='Will the Republican Party win the CA-23 House seat?' WHERE event_id='CM-EVT-X824QSSRY4';
UPDATE events SET question='Will the Democratic Party win the CA-26 House seat?' WHERE event_id='CM-EVT-L09J1013Z8';
UPDATE events SET question='Will the Republican Party win the CA-28 House seat?' WHERE event_id='CM-EVT-Z883X9PR44';
UPDATE events SET question='Will the Republican Party win the CA-30 House seat?' WHERE event_id='CM-EVT-TH8V4WGNY8';
UPDATE events SET question='Will the Republican Party win the CA-32 House seat?' WHERE event_id='CM-EVT-JC0HPQR1P0';
UPDATE events SET question='Will the Republican Party win the CA-34 House seat?' WHERE event_id='CM-EVT-DPBK0TXVR2';
UPDATE events SET question='Will the Democratic Party win the CA-39 House seat?' WHERE event_id='CM-EVT-Z5DKF1MM40';
UPDATE events SET question='Will the Democratic Party win the CA-48 House seat?' WHERE event_id='CM-EVT-STC090QDR6';
UPDATE events SET question='Will the Democratic Party win the CA-50 House seat?' WHERE event_id='CM-EVT-56LVM67BN7';
UPDATE events SET question='Will the Democratic Party win the CA-52 House seat?' WHERE event_id='CM-EVT-MYZ256V0C8';
UPDATE events SET question='Will the Democratic Party win the CO-07 House seat?' WHERE event_id='CM-EVT-BL0XD63R33';
UPDATE events SET question='Will the Republican Party win the FL-03 House seat?' WHERE event_id='CM-EVT-FFX2JPWD24';
UPDATE events SET question='Will the Republican Party win the FL-09 House seat?' WHERE event_id='CM-EVT-3ZLX48RMQ5';
UPDATE events SET question='Will the Republican Party win the FL-18 House seat?' WHERE event_id='CM-EVT-VDWZLZ0SR0';
UPDATE events SET question='Will the Republican Party win the FL-24 House seat?' WHERE event_id='CM-EVT-BRPD17VZ99';
UPDATE events SET question='Will the Republican Party win the GA-01 House seat?' WHERE event_id='CM-EVT-JR27YRTX92';
UPDATE events SET question='Will the Republican Party win the GA-03 House seat?' WHERE event_id='CM-EVT-P19NPKJY82';
UPDATE events SET question='Will the Republican Party win the GA-05 House seat?' WHERE event_id='CM-EVT-C5PKG52NM4';
UPDATE events SET question='Will the Republican Party win the GA-07 House seat?' WHERE event_id='CM-EVT-XL32STZ886';
UPDATE events SET question='Will the Democratic Party win the GA-08 House seat?' WHERE event_id='CM-EVT-N8M4BV6KL8';
UPDATE events SET question='Will the Republican Party win the GA-13 House seat?' WHERE event_id='CM-EVT-0NNGSZ5418';
UPDATE events SET question='Will the Republican Party win the HI-01 House seat?' WHERE event_id='CM-EVT-DYT8RDXNC8';
UPDATE events SET question='Will the Democratic Party win the HI-02 House seat?' WHERE event_id='CM-EVT-7HJG6TFXV0';
UPDATE events SET question='Will the Republican Party win the IL-02 House seat?' WHERE event_id='CM-EVT-YXKD4G0194';
UPDATE events SET question='Will the Republican Party win the IL-03 House seat?' WHERE event_id='CM-EVT-N627S4DQ18';
UPDATE events SET question='Will the Democratic Party win the IL-04 House seat?' WHERE event_id='CM-EVT-KQCXV5X5Z2';
UPDATE events SET question='Will the Republican Party win the IL-06 House seat?' WHERE event_id='CM-EVT-FDT1Z5MJX9';
UPDATE events SET question='Will the Democratic Party win the IL-10 House seat?' WHERE event_id='CM-EVT-61GVK45R17';
UPDATE events SET question='Will the Republican Party win the IL-11 House seat?' WHERE event_id='CM-EVT-5SQQNDKMJ7';
UPDATE events SET question='Will the Democratic Party win the IL-12 House seat?' WHERE event_id='CM-EVT-ZB906KHD21';
UPDATE events SET question='Will the Democratic Party win the IL-16 House seat?' WHERE event_id='CM-EVT-F04Q02GR20';
UPDATE events SET question='Will the Republican Party win the IN-08 House seat?' WHERE event_id='CM-EVT-7LDXQ82782';
UPDATE events SET question='Will the Republican Party win the KY-01 House seat?' WHERE event_id='CM-EVT-76185RHZG9';
UPDATE events SET question='Will the Democratic Party win the KY-06 House seat?' WHERE event_id='CM-EVT-DKZ51ZN993';
UPDATE events SET question='Will the Democratic Party win the LA-03 House seat?' WHERE event_id='CM-EVT-LV760YX1D7';
UPDATE events SET question='Will the Republican Party win the LA-06 House seat?' WHERE event_id='CM-EVT-0QDL1MP980';
UPDATE events SET question='Will the Republican Party win the MI-02 House seat?' WHERE event_id='CM-EVT-P8GN18S3R2';
UPDATE events SET question='Will the Democratic Party win the MI-12 House seat?' WHERE event_id='CM-EVT-23J2Y0DDX4';
UPDATE events SET question='Will the Democratic Party win the MI-13 House seat?' WHERE event_id='CM-EVT-GWSC1C6GC9';
UPDATE events SET question='Will the Republican Party win the MO-07 House seat?' WHERE event_id='CM-EVT-DWMZ6PXBJ9';
UPDATE events SET question='Will the Democratic Party win the NC-04 House seat?' WHERE event_id='CM-EVT-NWW6JR41T9';
UPDATE events SET question='Will the Democratic Party win the NC-07 House seat?' WHERE event_id='CM-EVT-9L1SW3NVQ0';
UPDATE events SET question='Will the Democratic Party win the NJ-01 House seat?' WHERE event_id='CM-EVT-GV5WCXK389';
UPDATE events SET question='Will the Democratic Party win the NJ-11 House seat?' WHERE event_id='CM-EVT-12ZH7XD9R7';
UPDATE events SET question='Will the Democratic Party win the NJ-12 House seat?' WHERE event_id='CM-EVT-LHZLGZN971';
UPDATE events SET question='Will the Democratic Party win the NM-01 House seat?' WHERE event_id='CM-EVT-2DK5FP52K4';
UPDATE events SET question='Will the Democratic Party win the NY-05 House seat?' WHERE event_id='CM-EVT-B7BLCWGNR0';
UPDATE events SET question='Will the Democratic Party win the NY-07 House seat?' WHERE event_id='CM-EVT-39318LKKX4';
UPDATE events SET question='Will the Democratic Party win the NY-09 House seat?' WHERE event_id='CM-EVT-HQXC5YXMB7';
UPDATE events SET question='Will the Republican Party win the NY-10 House seat?' WHERE event_id='CM-EVT-HX8W0NQ7F0';
UPDATE events SET question='Will the Democratic Party win the NY-12 House seat?' WHERE event_id='CM-EVT-SQPSVYJHZ7';
UPDATE events SET question='Will the Democratic Party win the NY-13 House seat?' WHERE event_id='CM-EVT-2J2CVTFZY4';
UPDATE events SET question='Will the Democratic Party win the NY-14 House seat?' WHERE event_id='CM-EVT-8QG5RMCT29';
UPDATE events SET question='Will the Democratic Party win the NY-15 House seat?' WHERE event_id='CM-EVT-YWTNJJDGN9';
UPDATE events SET question='Will the Democratic Party win the NY-25 House seat?' WHERE event_id='CM-EVT-1RF5RFG8G4';
UPDATE events SET question='Will the Democratic Party win the NY-26 House seat?' WHERE event_id='CM-EVT-18T84RSTM7';
UPDATE events SET question='Will the Democratic Party win the OH-02 House seat?' WHERE event_id='CM-EVT-8MYX8LFZ81';
UPDATE events SET question='Will the Democratic Party win the OH-07 House seat?' WHERE event_id='CM-EVT-X8SB4C7Q71';
UPDATE events SET question='Will the Republican Party win the OH-14 House seat?' WHERE event_id='CM-EVT-PQSYDD15R9';
UPDATE events SET question='Will the Republican Party win the OK-04 House seat?' WHERE event_id='CM-EVT-TJ0R6396H3';
UPDATE events SET question='Will the Republican Party win the PA-02 House seat?' WHERE event_id='CM-EVT-VDPWXQTBG5';
UPDATE events SET question='Will the Democratic Party win the PA-03 House seat?' WHERE event_id='CM-EVT-WHRK1267V4';
UPDATE events SET question='Will the Republican Party win the PA-05 House seat?' WHERE event_id='CM-EVT-7MXYCF6YW9';
UPDATE events SET question='Will the Republican Party win the PA-09 House seat?' WHERE event_id='CM-EVT-93KMG08268';
UPDATE events SET question='Will the Democratic Party win the SC-01 House seat?' WHERE event_id='CM-EVT-FHSKN81YG1';
UPDATE events SET question='Will the Republican Party win the SC-04 House seat?' WHERE event_id='CM-EVT-M9H29CGSY2';
UPDATE events SET question='Will the Republican Party win the TN-01 House seat?' WHERE event_id='CM-EVT-QGRWNVMDQ5';
UPDATE events SET question='Will the Republican Party win the TN-02 House seat?' WHERE event_id='CM-EVT-CGMV0PWSK9';
UPDATE events SET question='Will the Republican Party win the TX-03 House seat?' WHERE event_id='CM-EVT-CQ7QFF82X6';
UPDATE events SET question='Will the Republican Party win the TX-05 House seat?' WHERE event_id='CM-EVT-6CD3TG69M5';
UPDATE events SET question='Will the Democratic Party win the TX-10 House seat?' WHERE event_id='CM-EVT-Q4X7333088';
UPDATE events SET question='Will the Democratic Party win the TX-11 House seat?' WHERE event_id='CM-EVT-T2C6YC2DM7';
UPDATE events SET question='Will the Democratic Party win the TX-13 House seat?' WHERE event_id='CM-EVT-Z8TCQBY184';
UPDATE events SET question='Will the Democratic Party win the TX-20 House seat?' WHERE event_id='CM-EVT-WVV3SXM5G2';
UPDATE events SET question='Will the Republican Party win the TX-31 House seat?' WHERE event_id='CM-EVT-3X6B1STW04';
UPDATE events SET question='Will the Democratic Party win the UT-04 House seat?' WHERE event_id='CM-EVT-782N7YSYX4';
UPDATE events SET question='Will the Democratic Party win the VA-05 House seat?' WHERE event_id='CM-EVT-T1XXBTBMR9';
UPDATE events SET question='Will the Republican Party win the VA-09 House seat?' WHERE event_id='CM-EVT-RJ9V409TH7';
UPDATE events SET question='Will the Democratic Party win the VA-11 House seat?' WHERE event_id='CM-EVT-BSRX8SFCC2';
UPDATE events SET question='Will the Democratic Party win the VT-AL House seat?' WHERE event_id='CM-EVT-Y1LJ9QYMB3';
UPDATE events SET question='Will the Democratic Party win the WA-01 House seat?' WHERE event_id='CM-EVT-FKZGFL5886';
UPDATE events SET question='Will the Democratic Party win the WA-10 House seat?' WHERE event_id='CM-EVT-LVR237F765';
UPDATE events SET question='Will the Democratic Party win the WI-02 House seat?' WHERE event_id='CM-EVT-7DLRD5K824';
UPDATE events SET question='Will the Republican Party win the WI-06 House seat?' WHERE event_id='CM-EVT-6QJ8Z4L1S9';
UPDATE events SET question='Will the Republican Party win the WI-07 House seat?' WHERE event_id='CM-EVT-Y39KV4JZ48';
UPDATE events SET question='Will Russia enter Havrylivka by February 28, 2026?' WHERE event_id='CM-EVT-6X6T1LBR85';
UPDATE events SET question='Will Russia capture Kupiansk-Vuzlovyi by March 31?' WHERE event_id='CM-EVT-V5ZY3B2XL1';
UPDATE events SET question='Tesla and SpaceX merger officially announced by June 30?' WHERE event_id='CM-EVT-2CLPLTTYR2';
UPDATE events SET question='Will Larry Page be 2nd richest person on December 31?' WHERE event_id='CM-EVT-B9YNB6V583';
UPDATE events SET question='Will Russia capture all of Ternuvate by February 28, 2026?' WHERE event_id='CM-EVT-CJ8RSC6LB7';
UPDATE events SET question='Will Russia capture Toretske by March 31, 2026?' WHERE event_id='CM-EVT-3P51BB7JL1';
UPDATE events SET question='Will Russia capture Sofiivka by March 31?' WHERE event_id='CM-EVT-DPHVXWXKM3';
UPDATE events SET question='Will Russia enter Kindrashivka by May 31?' WHERE event_id='CM-EVT-DR6DG1TLZ1';
UPDATE events SET question='Will Russia capture all of Huliaipole by February 28?' WHERE event_id='CM-EVT-TVK27N2C00';
UPDATE events SET question='Will GBP/USD hit 1.25 (Low) in 2026?' WHERE event_id='CM-EVT-KT9PQWHPJ3';
UPDATE events SET question='Will SpaceX’s initial public offering occur in June 2026 (ET)?' WHERE event_id='CM-EVT-5B0F2RXN89';
UPDATE events SET question='Elon Bull Run Parlay' WHERE event_id='CM-EVT-NVR4MFSHW1';
UPDATE events SET question='Will Russia enter Pokrovskoe by February 28, 2026?' WHERE event_id='CM-EVT-BZ1CKVQNR0';
UPDATE events SET question='Will Russia enter Khatnie by February 28, 2026?' WHERE event_id='CM-EVT-KR1P3ML5Y6';
UPDATE events SET question='Will Russia capture Pokrovka by February 28?' WHERE event_id='CM-EVT-S1VTV6Z255';
UPDATE events SET question='Will the People Power Party win 2 seats in South Korea’s June 3, 2026 parliamentary by-elections?' WHERE event_id='CM-EVT-1GJQ4GRTJ5';
UPDATE events SET question='Will Russia enter Ternuvate again by March 31?' WHERE event_id='CM-EVT-X0RWN18YF9';
UPDATE events SET question='Will Jay-Z be confirmed to have visited Epstein’s island?' WHERE event_id='CM-EVT-GB99Y1HPT3';
UPDATE events SET question='Will Samuel Alito announce his retirement by March 31, 2026?' WHERE event_id='CM-EVT-XDBQBGP715';
UPDATE events SET question='Will Russia capture all of Kostyantynivka by June 30, 2026?' WHERE event_id='CM-EVT-FCJZNBGRJ3';
UPDATE events SET question='Will Russia capture all of Lyman by December 31, 2026?' WHERE event_id='CM-EVT-P275PM3SZ2';
UPDATE events SET question='Will Russia enter Krasnopillya by May 31?' WHERE event_id='CM-EVT-X5WM459DG3';
UPDATE events SET question='Will Russia enter Mykhailivka by April 30?' WHERE event_id='CM-EVT-DQKBTL8TB7';
UPDATE events SET question='Will Russia capture Kindrativka by May 31?' WHERE event_id='CM-EVT-DJQZ4RN221';
UPDATE events SET question='Prince Andrew sentenced to prison?' WHERE event_id='CM-EVT-GDQSNTGK08';
UPDATE events SET question='Romanian PM Bolojan out by December 31?' WHERE event_id='CM-EVT-JVYZGZ2NK4';
UPDATE events SET question='Will Russia enter Stinky by May 31?' WHERE event_id='CM-EVT-KVQT8F1GV2';
UPDATE events SET question='Pakistan x Afghanistan ceasefire by March 31?' WHERE event_id='CM-EVT-Y5V7CQ4ZL2';
UPDATE events SET question='Will Robert Lebovics be the Republican nominee for Senate in New Jersey?' WHERE event_id='CM-EVT-YFX5YMRLR7';
UPDATE events SET question='Kurds declare independence from Iran?' WHERE event_id='CM-EVT-6CS49PPP18';
UPDATE events SET question='Will Russia capture Viroliubivka by March 31?' WHERE event_id='CM-EVT-4RTZBQZ8J8';
UPDATE events SET question='Will Russia enter Novyi Donbas by April 30?' WHERE event_id='CM-EVT-5TZL9NR6M5';
UPDATE events SET question='Hamad bin Isa Al Khalifa out as leader of Bahrain by June 30, 2026?' WHERE event_id='CM-EVT-VFHHKCVH97';
UPDATE events SET question='Will Anthropic make a deal with the Pentagon by April 30?' WHERE event_id='CM-EVT-42QJ4QFXW8';
UPDATE events SET question='Nechirvan Barzani out as Kurdistan Regional Government President?' WHERE event_id='CM-EVT-GTT2ZNFN87';
UPDATE events SET question='Iran leadership change by April 30?' WHERE event_id='CM-EVT-TYRP27H901';
UPDATE events SET question='Will Russia enter Shevchenko by May 31?' WHERE event_id='CM-EVT-ZD3KRN1JZ2';
UPDATE events SET question='Will Russia enter Svitle by May 31?' WHERE event_id='CM-EVT-P24LL026W8';
UPDATE events SET question='Will Russia enter Krasnoiarske by May 31?' WHERE event_id='CM-EVT-9451XCR6X5';
UPDATE events SET question='Will Predict.fun launch a token by June 30, 2026?' WHERE event_id='CM-EVT-YKCXX1PMH9';
UPDATE events SET question='US x Cuba economic deal by June 30, 2026?' WHERE event_id='CM-EVT-Y5QG71JGD0';
UPDATE events SET question='Will Israel launch a ground operation in Iran by April 30, 2026?' WHERE event_id='CM-EVT-57R7MW8CZ7';
UPDATE events SET question='SEC removes quarterly reporting requirement?' WHERE event_id='CM-EVT-DG943QH5Q6';
UPDATE events SET question='Will Steve Daines be the next Senate Majority Leader?' WHERE event_id='CM-EVT-ZZZ60Y4302';
UPDATE events SET question='Will Gustavo Petro be charged in the US by April 30?' WHERE event_id='CM-EVT-54THM2DWC0';
UPDATE events SET question='Will Russia enter Vasylivka by May 31, 2026?' WHERE event_id='CM-EVT-DQ5GH07P73';
UPDATE events SET question='Will Russia enter Novooleksandrivka by May 31, 2026?' WHERE event_id='CM-EVT-RLT67B3Z02';
UPDATE events SET question='Will Mohammed bin Salman cease to be the de facto leader of Saudi Arabia by June 30, 2026?' WHERE event_id='CM-EVT-7TQCR95JL6';
UPDATE events SET question='Thai Constitutional Court invalidates election?' WHERE event_id='CM-EVT-36W2VP3FB1';
UPDATE events SET question='Iran agrees to surrender enriched uranium stockpile by April 30, 2026?' WHERE event_id='CM-EVT-Z3K4DFFZY1';
UPDATE events SET question='US obtains Iranian enriched uranium by May 31?' WHERE event_id='CM-EVT-38HGT3RJ52';
UPDATE events SET question='Evo Morales arrested by May 31?' WHERE event_id='CM-EVT-C4G9GB6110';
UPDATE events SET question='Will Brad Bradford win the 2026 Toronto mayoral election?' WHERE event_id='CM-EVT-MDRDNHNYP1';
UPDATE events SET question='Will Russia capture all of Hryshyne by April 30?' WHERE event_id='CM-EVT-7H2690RJG2';
UPDATE events SET question='Will Moonshot AI’s Kimi K3 model be released by April 30, 2026?' WHERE event_id='CM-EVT-DYW729BW25';
UPDATE events SET question='Will Tesla deliver between 400000 and 425000 vehicles in Q2 2026' WHERE event_id='CM-EVT-TKB6WQH0P3';
UPDATE events SET question='Will Caroline Elliott win the 2026 Conservative Party of British Columbia leadership election?' WHERE event_id='CM-EVT-3RS4P5HFD0';
UPDATE events SET question='US x Iran permanent peace deal by May 31, 2026?' WHERE event_id='CM-EVT-TQTJ2MLTV8';
UPDATE events SET question='Will Pam Bondi be held in contempt of Congress by April 30?' WHERE event_id='CM-EVT-3DXZY73WZ9';
UPDATE events SET question='Will no qualifying diplomatic US-Iran meeting occur by June 30, 2026?' WHERE event_id='CM-EVT-1RQNR30Q04';
UPDATE events SET question='Will Russia enter Moskovka by May 31?' WHERE event_id='CM-EVT-V4V739KZH7';
UPDATE events SET question='Will Anthropic have the third best AI model at the end of June 2026?' WHERE event_id='CM-EVT-ZPS1JW41R7';
UPDATE events SET question='Will Anthropic have the third best AI model at the end of May 2026?' WHERE event_id='CM-EVT-1KFJXHGVF3';
UPDATE events SET question='Will J.D. Vance attend the next US x Iran diplomatic meeting?' WHERE event_id='CM-EVT-QXGNCCXT21';
UPDATE events SET question='Will Anthropic have closed its next funding round by December 31, 2026?' WHERE event_id='CM-EVT-DXDS5GW0C3';
UPDATE events SET question='Will Trump try to fire Powell as Fed Board Member by June 30, 2026?' WHERE event_id='CM-EVT-HLSMT21CB5';
UPDATE events SET question='Israel x Hezbollah permanent peace deal by May 31, 2026?' WHERE event_id='CM-EVT-BF4L8F7890';
UPDATE events SET question='Israel x Iran permanent peace deal by May 31, 2026?' WHERE event_id='CM-EVT-6BZBWX4DV3';
UPDATE events SET question='Israel withdraws from Lebanon by May 31, 2026?' WHERE event_id='CM-EVT-DYN9QZ3X25';
UPDATE events SET question='Israel x Hezbollah diplomatic meeting by April 26, 2026?' WHERE event_id='CM-EVT-9Z1YP279S2';
UPDATE events SET question='Over $800M crypto hack value in 2026?' WHERE event_id='CM-EVT-88PZ3D88F1';
UPDATE events SET question='Will Édouard Philippe be on the ballot for the 2027 French presidential election?' WHERE event_id='CM-EVT-6Q8LZ5QQW0';
UPDATE events SET question='Will Donald Trump publicly insult someone on May 7, 2026?' WHERE event_id='CM-EVT-2JB94MP7L6';
UPDATE events SET question='Will Lee Jang-woo win the 2026 Daejeon mayoral election?' WHERE event_id='CM-EVT-P65QWT6ZC3';
UPDATE events SET question='Will Kim Sang-wook win the 2026 Ulsan mayoral election?' WHERE event_id='CM-EVT-LS0LPXT4G2';
UPDATE events SET question='Will Xi meet with Takaichi by June 30, 2026?' WHERE event_id='CM-EVT-YYDL3L3G73';
UPDATE events SET question='Will Netflix, Inc. (NFLX) hit (LOW) $85 in May?' WHERE event_id='CM-EVT-5WKFZ54PN2';
UPDATE events SET question='Will Fernando Haddad win the 2026 São Paulo gubernatorial election?' WHERE event_id='CM-EVT-WWMKBBXKQ7';
UPDATE events SET question='Will Alexandre Kalil win the 2026 Minas Gerais gubernatorial election?' WHERE event_id='CM-EVT-S4L4VK6RC3';
UPDATE events SET question='Will Jerônimo Rodrigues win the 2026 Bahia gubernatorial election?' WHERE event_id='CM-EVT-BSZ53QYGS1';
UPDATE events SET question='Will Ciro Gomes win the 2026 Ceará gubernatorial election?' WHERE event_id='CM-EVT-VLWGV62PH5';
UPDATE events SET question='Trump renames ICE to NICE by June 30?' WHERE event_id='CM-EVT-2J5T71W5G2';
UPDATE events SET question='GPT-5.6 released by July 31, 2026?' WHERE event_id='CM-EVT-8SRXQ1F784';
UPDATE events SET question='Will Donald Trump sign an executive order on May 7, 2026?' WHERE event_id='CM-EVT-1G0JBGB7X0';
UPDATE events SET question='Will a new Gemini flagship be released by May 22, 2026?' WHERE event_id='CM-EVT-43HYTGHWR5';
UPDATE events SET question='Another critical Cloudflare incident by May 31, 2026?' WHERE event_id='CM-EVT-8DKHLXP492';
UPDATE events SET question='Will Trump speak to Xi Jinping in May?' WHERE event_id='CM-EVT-2G67Q7H6Z9';
UPDATE events SET question='Will Trump meet with Kim Jong Un in May 2026?' WHERE event_id='CM-EVT-D53VJLCPC3';
UPDATE events SET question='Will Elon Musk’s net worth be at least $690b on May 31?' WHERE event_id='CM-EVT-D44K84H8H7';
UPDATE events SET question='Will there be between 0 and 10 average daily transits of the Strait of Hormuz on May 31?' WHERE event_id='CM-EVT-VL4JS2Y9L6';
UPDATE events SET question='Will gas hit (High) $4.45 by May 31?' WHERE event_id='CM-EVT-T0Z4DKV587';
UPDATE events SET question='Will Crude Oil reach a new all-time high by May 31?' WHERE event_id='CM-EVT-2179JPSW74';
UPDATE events SET question='Will JD Vance have a diplomatic meeting with Iran by May 31, 2026?' WHERE event_id='CM-EVT-L5P0145HC0';
UPDATE events SET question='Ruben Rocha out as Governor of Sinaloa by May 31?' WHERE event_id='CM-EVT-TX23QTZQM6';
UPDATE events SET question='Sinaloa Gov. Ruben Rocha arrested by May 31?' WHERE event_id='CM-EVT-5XFYY6MBJ5';
UPDATE events SET question='Sinaloa Gov. Ruben Rocha extradited to US by May 15?' WHERE event_id='CM-EVT-GHYT29QKW0';
UPDATE events SET question='Will Javier Milei win the 2027 Argentina presidential election?' WHERE event_id='CM-EVT-6Y6JDSVW06';
UPDATE events SET question='Iran closes its airspace by May 24?' WHERE event_id='CM-EVT-K27M9N6KW4';
UPDATE events SET question='Will Marine Tondelier be the joint left nominee for the 2027 French presidential election?' WHERE event_id='CM-EVT-WGPTXTJYH0';
UPDATE events SET question='Will Bernard Drainville be the next Premier of Quebec following the 2026 Quebec general election?' WHERE event_id='CM-EVT-X4XRMN8RJ9';
UPDATE events SET question='Andy Burnham out as Mayor of Greater Manchester by May 31?' WHERE event_id='CM-EVT-FXYXDF9530';
UPDATE events SET question='DOJ reopens Powell investigation by May 15?' WHERE event_id='CM-EVT-1JXF3GBLZ3';
UPDATE events SET question='Russia x Ukraine diplomatic meeting by May 31, 2026?' WHERE event_id='CM-EVT-FN0YJT28Q5';
UPDATE events SET question='Israel closes its airspace by May 31?' WHERE event_id='CM-EVT-347V41ZS21';
UPDATE events SET question='Trump orders federal review of AI model releases by May 31?' WHERE event_id='CM-EVT-7V2XTJKR93';
UPDATE events SET question='Will Russia capture all of Rodynske again by June 30?' WHERE event_id='CM-EVT-FDYKMTRPT4';
UPDATE events SET question='Over $250k committed to the ALIGN public sale?' WHERE event_id='CM-EVT-3LDXH90Y48';
UPDATE events SET question='Russia x Ukraine ceasefire agreement by May 31, 2026?' WHERE event_id='CM-EVT-LVRHCH4653';
UPDATE events SET question='Will the Labour Party win the next Maltese general election by 5-10%?' WHERE event_id='CM-EVT-27L3NZPXY8';
UPDATE events SET question='Will the Democratic Party win 10 or fewer upper-level local government races?' WHERE event_id='CM-EVT-09FC88QK86';
UPDATE events SET question='AI data center in space by December 31, 2027?' WHERE event_id='CM-EVT-CKXBJJF168';
UPDATE events SET question='Will Dell Q1 Infrastructure Solutions Group revenue be above $23.5B?' WHERE event_id='CM-EVT-NQFKHXCQ53';
UPDATE events SET question='Will Rebecca Shepherd win the 2026 Makerfield by-election?' WHERE event_id='CM-EVT-LY608MSMM2';
UPDATE events SET question='Jung Chung-rae out as DP leader by December 31, 2026?' WHERE event_id='CM-EVT-YD97MDSYH6';
UPDATE events SET question='Russia x Ukraine ceasefire by June 30, 2026?' WHERE event_id='CM-EVT-2089XJ01Y3';
UPDATE events SET question='Saudi Arabia bans US military aircraft by May 31?' WHERE event_id='CM-EVT-V7W8T6VMN4';
UPDATE events SET question='Will Alphabet be the second-largest company in the world by market cap on June 30?' WHERE event_id='CM-EVT-5MSNF28G94';
UPDATE events SET question='U.S. anti-cartel operation outside of the U.S. by May 31?' WHERE event_id='CM-EVT-T52F2Q2VT2';
UPDATE events SET question='Will Broadcom Q2 AI revenue be above $11.0B?' WHERE event_id='CM-EVT-5Q2P15LK56';
UPDATE events SET question='Ex-Cuba leader Raul Castro in US custody by June 30?' WHERE event_id='CM-EVT-3S08F14384';
UPDATE events SET question='Will OpenAI''s valuation hit (LOW) $750B by December 31?' WHERE event_id='CM-EVT-MSMC7NQ0P3';
UPDATE events SET question='Will Stripe''s valuation hit (HIGH) $190B by December 31?' WHERE event_id='CM-EVT-4PJ936LPW5';
UPDATE events SET question='Will Anduril''s valuation hit (HIGH) $100B by December 31?' WHERE event_id='CM-EVT-NGQFWL8SV2';
UPDATE events SET question='Rodrigo Paz out as President of Bolivia by May 31, 2026?' WHERE event_id='CM-EVT-6S4M4CJVM9';
UPDATE events SET question='Will Prabowo Subianto cease to be President of Indonesia by May 31, 2026?' WHERE event_id='CM-EVT-G1Z8SHB372';
UPDATE events SET question='Will Russia capture Mala Tokmachka by June 30, 2026?' WHERE event_id='CM-EVT-LZJNH4HTZ3';
UPDATE events SET question='Will the price of Bitcoin be between $68,000 and $70,000 on May 28?' WHERE event_id='CM-EVT-TRJSRPMW64';
UPDATE events SET question='Will the price of Ethereum be between $2,500 and $2,600 on May 28?' WHERE event_id='CM-EVT-WHTJ2MBYP4';
UPDATE events SET question='Will the House pass a reconciliation bill by May 31?' WHERE event_id='CM-EVT-M7B92PFZP2';
UPDATE events SET question='US x Cuba diplomatic meeting by May 31?' WHERE event_id='CM-EVT-VD96ST34J5';
UPDATE events SET question='Will Micron Q3 NAND revenue be above $8.0B?' WHERE event_id='CM-EVT-L1ZYNSRRT3';
UPDATE events SET question='Will Trump announce Elise Stefanik as the next Director of National Intelligence?' WHERE event_id='CM-EVT-RT2VPS5DM7';
UPDATE events SET question='Will Elon Musk post 20-39 tweets in July 2026?' WHERE event_id='CM-EVT-5HV3KF4YB2';
UPDATE events SET question='Will Elon Musk post 190-214 tweets from May 28 to May 30, 2026?' WHERE event_id='CM-EVT-D9FJBY7S11';
UPDATE events SET question='Will Elon Musk post 500+ tweets from May 29 to June 5, 2026?' WHERE event_id='CM-EVT-H8KG2NJPG7';
