UPDATE events SET question='Will Meta Platforms, Inc. report above 65000 Headcount in 2026?' WHERE event_id='CM-EVT-TMQV3GL3H5';
UPDATE events SET question='Will United Airlines Holdings Inc. report Above 180 million passengers flown in 2026?' WHERE event_id='CM-EVT-XL3H4QDNB2';
UPDATE events SET question='Will Starbucks Corporation report Above 41300 total global stores in 2026?' WHERE event_id='CM-EVT-KLZTSTHRW4';
UPDATE events SET question='Will Rivian Automotive Inc. report Above 46000 total vehicles delivered in 2026?' WHERE event_id='CM-EVT-MNW3V0NLZ3';
UPDATE events SET question='Will Ferrari N.V. report Above 13500 total car shipments in 2026?' WHERE event_id='CM-EVT-S0J9Z4Z8L9';
UPDATE events SET question='Will Palantir Technologies Inc. report Above 1100 total customer count in 2026?' WHERE event_id='CM-EVT-GRYBMRR7N8';
UPDATE events SET question='Will MercadoLibre Inc. report Above 3 billion items sold in 2026?' WHERE event_id='CM-EVT-B77SNX3N32';
UPDATE events SET question='Will Ford Motor Company report Above 1.8 million u.s. vehicle sales volume in 2026?' WHERE event_id='CM-EVT-GZLYPGCNW4';
UPDATE events SET question='Will Boeing Company (The) report Above 620 commercial airplane deliveries in 2026?' WHERE event_id='CM-EVT-XC5LD6MTP5';
UPDATE events SET question='Will Netflix, Inc. report above 16500 total full-time employees in 2026?' WHERE event_id='CM-EVT-YCRTYGM6L4';
UPDATE events SET question='Will Blue and White be a part of the next government in Israel?' WHERE event_id='CM-EVT-Z3SNG6NMQ8';
UPDATE events SET question='Will Amazon.com, Inc. report above 1500000 Employees (full-time and part-time; excludes contractors & temporary personnel) in 2026?' WHERE event_id='CM-EVT-H1RM2B2RT0';
UPDATE events SET question='Who will run for the Democratic presidential nomination in 2028?' WHERE event_id='CM-EVT-5H09B63413';
UPDATE events SET question='Will the margin of victory for Republicans in the U.S. Senate election in South Carolina be at least 5 percentage points?' WHERE event_id='CM-EVT-20CYP3Z7L1';
UPDATE events SET question='Will the margin of victory for Democrats in the Oregon''s 3rd District House election be at least 38 percentage points?' WHERE event_id='CM-EVT-98TTCLWRD8';
UPDATE events SET question='Will the margin of victory for Democrats in the Ohio''s 13th District House election be at least 8 percentage points?' WHERE event_id='CM-EVT-RL4DPXZ231';
UPDATE events SET question='Will the margin of victory for Democrats in the New Hampshire''s 2nd District House election be at least 4 percentage points?' WHERE event_id='CM-EVT-PQ0MKZ50Q6';
UPDATE events SET question='Will the margin of victory for Democrats in the Minnesota''s 2nd District House election be at least 13 percentage points?' WHERE event_id='CM-EVT-3YTF9WJQ37';
UPDATE events SET question='Will the margin of victory for Democrats in the Kansas''s 3rd District House election be at least 8 percentage points?' WHERE event_id='CM-EVT-V0LHDFSSG6';
UPDATE events SET question='Will the margin of victory for Republicans in the Indiana''s 5th District House election be at least 1 percentage points?' WHERE event_id='CM-EVT-S26P9Y15Q9';
UPDATE events SET question='Will the margin of victory for Democrats in the Connecticut''s 1st District House election be at least 22 percentage points?' WHERE event_id='CM-EVT-92PYSZMSS2';
UPDATE events SET question='Will the margin of victory for Republicans in the Arkansas''s 3rd District House election be at least 19 percentage points?' WHERE event_id='CM-EVT-BL6HFHK4H3';
UPDATE events SET question='Will the margin of victory for Jared Moskowitz in the 2026 FL-25 Democratic primary be at least 5%?' WHERE event_id='CM-EVT-47SC7ZB7M9';
UPDATE events SET question='Will Francesca Hong receive at least 25% of the popular vote in the 2026 Wisconsin Democratic gubernatorial primary?' WHERE event_id='CM-EVT-H192MQKBR8';
UPDATE events SET question='Will the margin of victory for Larry Rhoden in the 2026 South Dakota Republican gubernatorial runoff be above 12%?' WHERE event_id='CM-EVT-RDKJ171883';
UPDATE events SET question='Will the monthly average compute price of NVIDIA''s B200 be above $3.00 in April 2027?' WHERE event_id='CM-EVT-JH65RKS354';
UPDATE events SET question='Will the monthly average compute price of NVIDIA''s B200 be above $3.00 in March 2027?' WHERE event_id='CM-EVT-D7FTMK9ZT7';
UPDATE events SET question='Will Talen Energy Corporation report Above 50 TWh total generation (twh) in fiscal 2026?' WHERE event_id='CM-EVT-09LNFQRWZ2';
UPDATE events SET question='Will the number of Trump rallies be above 15 from January 1 to November 3, 2026?' WHERE event_id='CM-EVT-8CL5HBK172';
UPDATE events SET question='Will the monthly average compute price of NVIDIA''s H200 be above $5.00 in January 2027?' WHERE event_id='CM-EVT-9QW6D6FSF2';
UPDATE events SET question='State of the economy at the end of 2026?' WHERE event_id='CM-EVT-ZRG5DFDMZ8';
UPDATE events SET question='How many oil rigs will the US have at the end of the year?' WHERE event_id='CM-EVT-7711L38BN5';
UPDATE events SET question='Will Donald Trump visit California before Jan 1, 2027?' WHERE event_id='CM-EVT-T39KCTYDG5';
UPDATE events SET question='Will Donald Trump meet in person Claudia Sheinbaum before Jan 1, 2027?' WHERE event_id='CM-EVT-WY1J5J92Q7';
UPDATE events SET question='Will Dem Nominee be Graham Platner AND General Election Winner be Democrat for Jan 2027?' WHERE event_id='CM-EVT-2KYR51YTD3';
UPDATE events SET question='Will John Brennan be arrested before Jan 2027?' WHERE event_id='CM-EVT-T101LW9G50';
UPDATE events SET question='ETH price  on Jan 1, 2027?' WHERE event_id='CM-EVT-M6M011NKR6';
UPDATE events SET question='BTC price  on Jan 1, 2027?' WHERE event_id='CM-EVT-0WKFGLC4Y3';
UPDATE events SET question='Will the monthly average compute price of NVIDIA''s H200 be above $1.50 in December 2026?' WHERE event_id='CM-EVT-NJ402DL9C2';
UPDATE events SET question='Will the B200 compute per hour price be above $6.47 by Dec 31?' WHERE event_id='CM-EVT-P62T0T1W52';
UPDATE events SET question='Will Bitcoin be above $99,999.99 by Dec 31, 2026 at 11:59 PM ET?' WHERE event_id='CM-EVT-0MWN62PNG9';
UPDATE events SET question='Will the Nasdaq-100 be above 28000 on Dec 31, 2026 at 4pm EST?' WHERE event_id='CM-EVT-GNKG1GYDT6';
UPDATE events SET question='Will the Nasdaq-100 be below 19000 at the end of Dec 31, 2026 at 4pm EST?' WHERE event_id='CM-EVT-JPWZDPJ339';
UPDATE events SET question='Will the S&P 500 be between 7800 and 7999.99 on Dec 31, 2026 at 4pm EST?' WHERE event_id='CM-EVT-K47V5LVKY9';
UPDATE events SET question='Will the price of WTI oil be above 75 on December 31, 2026 at 02:30 PM EST?' WHERE event_id='CM-EVT-N12K7YZCV3';
UPDATE events SET question='Will any LLM score at least 50% on Humanity''s Last Exam before Dec 31, 2026?' WHERE event_id='CM-EVT-M5L4WJM110';
UPDATE events SET question='Who will win the governorship in Alaska?' WHERE event_id='CM-EVT-B206SG3QQ3';
UPDATE events SET question='Will there be more than 10  Atlantic hurricanes in 2026?' WHERE event_id='CM-EVT-Q08SZJTP95';
UPDATE events SET question='Will the monthly average compute price of NVIDIA''s B200 be above $3.00 in November 2026?' WHERE event_id='CM-EVT-XG55LPZ6X5';
UPDATE events SET question='Will Talarico for Texas report more than $25M in total receipts during Q3?' WHERE event_id='CM-EVT-67BKV1R8H3';
UPDATE events SET question='Will John E. Sununu be the Republican nominee for the Senate in New Hampshire?' WHERE event_id='CM-EVT-TJYWW9Y1N3';
UPDATE events SET question='Will the monthly average compute price of NVIDIA''s H200 be above $3.00 in October 2026?' WHERE event_id='CM-EVT-WHCKZ77Y03';
UPDATE events SET question='Will the unemployment rate (U-3) be above 4.0% in September?' WHERE event_id='CM-EVT-720DZC17Y9';
UPDATE events SET question='Donald Trump and Mohammed bin Salman meet before Sep 1, 2026?' WHERE event_id='CM-EVT-4WYVLJ0YX7';
UPDATE events SET question='How many launches will SpaceX have in Aug 2026?' WHERE event_id='CM-EVT-44DGF8Z1F9';
UPDATE events SET question='Will DoorDash Inc. report above 940 million total orders in Q2 2026?' WHERE event_id='CM-EVT-GKGRRKSX88';
UPDATE events SET question='Will Trump make 0 trips to Mar-a-Lago as President in Aug 2026?' WHERE event_id='CM-EVT-BD8VLVHC95';
UPDATE events SET question='Will BTC trimmed mean be below $60000.00 by 11:59 PM ET on Aug 31, 2026?' WHERE event_id='CM-EVT-9D8FRK3QR0';
UPDATE events SET question='Will the monthly average compute price of NVIDIA''s B200 be above $3.00 in August 2026?' WHERE event_id='CM-EVT-33JMMK5181';
UPDATE events SET question='Will the gold close price be above 4011.99 USD/t.oz on August 31, 2026 at 5:00 PM EDT?' WHERE event_id='CM-EVT-SQ3CSQLZF7';
UPDATE events SET question='Will the NVIDIA A100 compute per hour price be above $0.5 at 4 PM ET on Aug 28?' WHERE event_id='CM-EVT-B3VVLZBXY0';
UPDATE events SET question='Will the NVIDIA RTX 5090 compute per hour price be above $0.25 at 4 PM ET on Aug 14?' WHERE event_id='CM-EVT-QYX5Z2CN29';
UPDATE events SET question='Will the NVIDIA H200 compute per hour price be above $2 at 4 PM ET on Aug 14?' WHERE event_id='CM-EVT-Y9FFP58N19';
UPDATE events SET question='Will the Truflation EV Commodity Index on Aug 4, 2026 be above 1211.89?' WHERE event_id='CM-EVT-FJ9H5KDRH5';
UPDATE events SET question='SOL price on Aug 7, 2026?' WHERE event_id='CM-EVT-YCV9BNLS18';
UPDATE events SET question='Ethereum price at Aug 7, 2026 at 5pm EDT?' WHERE event_id='CM-EVT-YJDJ26D182';
UPDATE events SET question='Bitcoin price on Aug 7, 2026?' WHERE event_id='CM-EVT-PFHRR5PCZ2';
UPDATE events SET question='Will the silver close price be above 46.99 USD/t.oz on August 07, 2026 at 5:00 PM EDT?' WHERE event_id='CM-EVT-K80TT5CVH2';
UPDATE events SET question='Will the natural gas close price be above 2.699 USD/MMBtu on August 07, 2026 at 5:00 PM EDT?' WHERE event_id='CM-EVT-LSBJJ424Z4';
UPDATE events SET question='Will the gold close price be above 3764.99 USD/t.oz on August 07, 2026 at 5:00 PM EDT?' WHERE event_id='CM-EVT-7GJL5NYRS6';
UPDATE events SET question='Will the brent crude oil close price be above 74.99 USD/Bbl on August 07, 2026 at 5:00 PM EDT?' WHERE event_id='CM-EVT-L06SJB3WP5';
UPDATE events SET question='Will the NVIDIA H100 compute per hour price be above $2.5 at 4 PM ET on Aug 07?' WHERE event_id='CM-EVT-K9XNGR8PC1';
UPDATE events SET question='Will the WTI crude oil settlement price be above 72.49 USD/Bbl on Aug 5, 2026?' WHERE event_id='CM-EVT-G92PJ6X7M2';
UPDATE events SET question='Will the Nasdaq-100 be above 28829.99 at the end of Aug 4, 2026 at 4pm EDT?' WHERE event_id='CM-EVT-D240059CW0';
UPDATE events SET question='SOL price on Aug 4, 2026?' WHERE event_id='CM-EVT-1SGC4H2X09';
UPDATE events SET question='Ethereum price at Aug 4, 2026 at 5pm EDT?' WHERE event_id='CM-EVT-1ZK24PBQT2';
UPDATE events SET question='Bitcoin price on Aug 4, 2026?' WHERE event_id='CM-EVT-SW0KNXLDZ6';
UPDATE events SET question='Will the silver close price be above 59.25 USD/t.oz on August 04, 2026 at 5:00 PM EDT?' WHERE event_id='CM-EVT-GCHCDBSG56';
UPDATE events SET question='Will the gold close price be above 4060 USD/t.oz on August 04, 2026 at 5:00 PM EDT?' WHERE event_id='CM-EVT-5FGB4M3446';
UPDATE events SET question='Will the copper close price be above 6.40 USD/Lbs on August 04, 2026 at 5:00 PM EDT?' WHERE event_id='CM-EVT-SPZB50N4Z4';
UPDATE events SET question='Will the brent crude oil close price be above 78.50 USD/Bbl on August 04, 2026 at 5:00 PM EDT?' WHERE event_id='CM-EVT-9ZHDY56JK9';
UPDATE events SET question='Will the WTI crude oil settlement price be above 75.49 USD/Bbl on Aug 4, 2026?' WHERE event_id='CM-EVT-SXK96C0623';
UPDATE events SET question='ZEC price up in next 15 mins?' WHERE event_id='CM-EVT-NJ8RP5ZZ47';
UPDATE events SET question='Will the temp in Washington DC be above 81.99° on Aug 4, 2026 at 2pm EDT?' WHERE event_id='CM-EVT-JL4K3B8TG5';
UPDATE events SET question='Will the temp in Chicago be above 80.99° on Aug 4, 2026 at 2pm EDT?' WHERE event_id='CM-EVT-6NB5ZKB019';
UPDATE events SET question='Will the temp in Austin be above 93.99° on Aug 4, 2026 at 2pm EDT?' WHERE event_id='CM-EVT-PGQH0YHYL3';
UPDATE events SET question='SOL price on Aug 4, 2026?' WHERE event_id='CM-EVT-LTKXT4SSZ5';
UPDATE events SET question='Ethereum price at Aug 4, 2026 at 2pm EDT?' WHERE event_id='CM-EVT-GVLM3S0LS6';
UPDATE events SET question='Bitcoin price on Aug 4, 2026?' WHERE event_id='CM-EVT-QR8B2N7KY8';
UPDATE events SET question='Will the WTI Oil close price be above 75.69 USD/barrel on August 04, 2026 at 2:00 PM ET?' WHERE event_id='CM-EVT-MTZZYZ8CB2';
UPDATE events SET question='Will the S&P 500 be above 7734.9999 on Aug 4, 2026 at 2pm EDT?' WHERE event_id='CM-EVT-1203RGVHZ4';
UPDATE events SET question='Will NVIDIA be the largest company in the world by market cap on December 31?' WHERE event_id='CM-EVT-WMBW6M11T5';
UPDATE events SET question='Will Paramount close Warner Bros acquisition?' WHERE event_id='CM-EVT-CP17BTS9G2';
UPDATE events SET question='Unit FDV above $200M one day after launch?' WHERE event_id='CM-EVT-0M39GH7W59';
UPDATE events SET question='Will USD/KRW hit 1500 (High) in 2026?' WHERE event_id='CM-EVT-PJB0JX5488';
UPDATE events SET question='Will USD/CAD hit 1.45 (High) in 2026?' WHERE event_id='CM-EVT-K34H6Z9YH8';
UPDATE events SET question='Will Russia enter Ternuvate again by March 31?' WHERE event_id='CM-EVT-X0RWN18YF9';
UPDATE events SET question='Will the sender of the “I beat Bush” email to Epstein not be revealed in 2026?' WHERE event_id='CM-EVT-C4JY7HLGG8';
UPDATE events SET question='Will Marine Le Pen be on the ballot for the 2027 French presidential election?' WHERE event_id='CM-EVT-6Q8LZ5QQW0';
UPDATE events SET question='Will Ciro Gomes win the 2026 Ceará gubernatorial election?' WHERE event_id='CM-EVT-VLWGV62PH5';
UPDATE events SET question='Will Anthropic''s valuation hit (HIGH) $3.0T by December 31?' WHERE event_id='CM-EVT-7Y9Q6XSHM9';
UPDATE events SET question='Will the median home value in Los Angeles Metro be between $1,185,000 and $1,201,000 on September 30?' WHERE event_id='CM-EVT-1K3DX8QVV3';
UPDATE events SET question='Will the median home value in the US be between $419,000 and $426,000 on September 30?' WHERE event_id='CM-EVT-RLDGCHYZ91';
UPDATE events SET question='Will the median home value in NYC be between $636,000 and $663,000 on September 30?' WHERE event_id='CM-EVT-7KQT47ZLX8';
UPDATE events SET question='Will the median home value in San Francisco Metro be less than $1,176,000 on September 30?' WHERE event_id='CM-EVT-T8H9TWR8Q2';
UPDATE events SET question='Will James Fishback win less than 10% of votes in the Florida Republican Governor primary?' WHERE event_id='CM-EVT-3C6QVGS040';
UPDATE events SET question='Will the US add between 50k and 100k jobs in July?' WHERE event_id='CM-EVT-T4MXZ9HS26';
UPDATE events SET question='Will Ted Cruz post 80-99 posts from July 31 to August 7, 2026?' WHERE event_id='CM-EVT-CDLCKXLMR7';
UPDATE events SET question='Will NYC Mayor post 40-59 posts from July 31 to August 7, 2026?' WHERE event_id='CM-EVT-P39SGJ96R5';
UPDATE events SET question='Will Elon Musk post 120-139 tweets from July 31 to August 7, 2026?' WHERE event_id='CM-EVT-GQ763JGFC6';
UPDATE events SET question='Will the price of Bitcoin be between $60,000 and $62,000 on August 5?' WHERE event_id='CM-EVT-0T3Z8XQV24';
UPDATE events SET question='Will the price of Bitcoin be between $60,000 and $62,000 on August 7?' WHERE event_id='CM-EVT-Q0LRC0PQJ3';
UPDATE events SET question='Will Apple (AAPL) hit (LOW) $300 Week of August 3 2026?' WHERE event_id='CM-EVT-97D5LP3WV8';
UPDATE events SET question='Will Elon Musk post <40 tweets from August 3 to August 5, 2026?' WHERE event_id='CM-EVT-3VSN3YF491';
UPDATE events SET question='Will the price of Bitcoin be above $58,000 on August 8?' WHERE event_id='CM-EVT-1K7F207KH9';
UPDATE events SET question='Will Elon Musk post 140-164 tweets from August 6 to August 8, 2026?' WHERE event_id='CM-EVT-D15HMT8LR6';
UPDATE events SET question='Will Francesca Hong win the Wisconsin Democratic Governor primary by at least 30%?' WHERE event_id='CM-EVT-BFGM989KC0';
UPDATE events SET question='Will Elon Musk post 60-79 tweets from August 4 to August 11, 2026?' WHERE event_id='CM-EVT-PM0S33YGH8';
UPDATE events SET question='Will there be fewer than 1 North Korea test in August 2026?' WHERE event_id='CM-EVT-V2QCKJ1C06';
UPDATE events SET question='Will Trump meet with Volodymyr Zelenskyy in August 2026?' WHERE event_id='CM-EVT-7VDLT6X0R5';
UPDATE events SET question='Will Trump speak to Andy Burnham in August?' WHERE event_id='CM-EVT-ZGK5CJV2L9';
UPDATE events SET question='Will there be between 0 and 20 average daily transits of the Strait of Hormuz on August 31?' WHERE event_id='CM-EVT-WDLVPKLWQ8';
