-- Reload-as-upsert columns on the LIVE tables (2026-10-08). Run ONCE before the first reload
-- generated by the upsert-era export-d1.mjs:
--   cd api && npx wrangler d1 execute clearmarket --remote --file=reload-upsert-migration.sql
-- SQLite ADD COLUMN has no IF NOT EXISTS: re-running errors harmlessly ("duplicate column name").
-- seed/schema.sql (regenerated) carries the same columns for a from-scratch DB.
--
-- events.bundle_vintage  : _meta.generated_at of the bundle that last wrote the row.
-- markets.bundle_vintage : same, for the row's description columns. Reload stamps it on every market
--                          it carries; the retirement UPDATE then delists still-open markets whose
--                          vintage was NOT refreshed (NULL counts as stale — pre-migration rows).
-- markets.delisted_at    : set (= the retiring vintage) when a still-open market is absent from a
--                          reload; cleared if the market reappears. Status 'delisted' is new: the
--                          Worker's live/open predicates all key on status = 'open', so delisted rows
--                          drop out of refresh, reconcile and the active set with no code change.
ALTER TABLE events ADD COLUMN bundle_vintage TEXT;
ALTER TABLE markets ADD COLUMN bundle_vintage TEXT;
ALTER TABLE markets ADD COLUMN delisted_at TEXT;
CREATE INDEX IF NOT EXISTS idx_markets_status ON markets(status);
CREATE INDEX IF NOT EXISTS idx_markets_vintage ON markets(bundle_vintage);
